import React, { createContext, useState, useContext } from 'react';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('digisaathi_lang') || 'en';
  });

  const setLang = (newLang) => {
    localStorage.setItem('digisaathi_lang', newLang);
    setLangState(newLang);
  };

    const t = (key) => {
    return (translations[lang] && translations[lang][key]) || 
           (LANGUAGES[lang] && LANGUAGES[lang][key]) || 
           (translations['en'] && translations['en'][key]) || 
           (LANGUAGES['en'] && LANGUAGES['en'][key]) || 
           key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export const LANGUAGES = {
  en: {
        "homeCareTitle": `Home Care Services`,
        "homeCareSubtitle": `Verified Help & Care at Your Doorstep`,
        "cleaningCat": `Cleaning Services`,
        "applianceCat": `Appliance Repair`,
        "medicineCat": `Medical & Health`,
        "convenienceCat": `Daily Convenience`,
        "safetyCat": `Safety & Emergency`,
        "Room Cleaning_sub": `Complete sweeping, mopping, and dusting for bedroom & living room.`,
        "Bathroom Cleaning_sub": `Deep cleaning, sanitization, and scrubbing of toilet & bathroom.`,
        "Kitchen Cleaning_sub": `Countertop, stove cleaning, and sink hygiene maintenance.`,
        "Deep Home Cleaning_sub": `Thorough deep cleaning of all rooms, windows, and corners.`,
        "Sofa Cleaning_sub": `Vacuuming and stain removal for sofas and armchairs.`,
        "Balcony Cleaning_sub": `Floor washing and plant area cleanup for balcony.`,
        "Floor Cleaning_sub": `Mopping and polishing for sparkling clean floors.`,
        "Stove Repair_sub": `Fixing gas leaks, burner ignition issues, and stove maintenance.`,
        "Fan Repair_sub": `Regulator issues, noise troubleshooting, and fan installation.`,
        "AC Repair_sub": `AC servicing, filter cleaning, and gas refill.`,
        "fontSize": `Font Size`,
        "gpsActive": `GPS Active`,
        "gpsSearching": `Searching GPS...`,
        "liveTracking": `Live Tracking`,
        "simMovement": `Simulate Walk`,
        "stopSimulation": `Stop Walk`,
        "shareWithFamily": `Share with Family`,
        "latitude": `Latitude`,
        "longitude": `Longitude`,
        "speed": `Speed`,
        "accuracy": `Accuracy`,
        "gpsActiveText": `Live GPS tracking activated. Finding your device signal...`,
        "gpsInactiveText": `Live tracking deactivated.`,
        "gpsErrorText": `GPS Signal weak. Please verify device location permissions.`,
        "simActiveText": `Simulating live device movement in Pune.`,
        "simInactiveText": `Simulation stopped.`,
        "currentLocSpoken": `Your current device location is`,
        "locationSharedSuccess": `Live location successfully shared with your trusted family!`,
        "alertInfoBanner": `Tap any alert to learn what to do. Speak guides are available inside.`,
        "staySafe": `Stay Safe Online`,
        "learnToIdentify": `Learn to identify and avoid scams`,
        "whatToDo": `What to do:`,
        "highSeverity": `High Alert`,
        "mediumSeverity": `Medium Alert`,
        "selectHelpService": `Select Help Service`,
        "scheduledFor": `Scheduled for`,
        "at": `at`,
        "today": `Today`,
        "tomorrow": `Tomorrow`,
        "immediate": `Immediate`,
        "addressLabel": `Address`,
        "ratingLabel": `Rating`,
        "callBtn": `Call`,
        "resetBtn": `Reset`,
        "recentlyUsed": `Recently Used (1-Tap Booking)`,
        "seniorsDeck": `Seniors Deck`,
        "oneTapBook": `1-Tap Book`,
        "noMatchingFound": `No matching services found.`,
        "trySearchingFor": `Try searching for "AC", "Cleaning", "Doctor", or "SOS".`,
        "availableNow": `Available Now`,
        "pricingPackages": `💰 Pricing Packages`,
        "bookSlotOption": `⏱ Book Slot Option`,
        "selectDateDay": `Select Date & Day`,
        "selectTimeSlot": `Select Time Slot`,
        "languagesLabel": `Languages`,
        "addressSelection": `👤 Address Selection`,
        "totalPackagesCost": `Total Packages Cost`,
        "confirmBooking": `Confirm Booking`,
        "optionsAvailable": `Options available`,
        "availableServices": `Available Services`,
        "closeBtn": `Close`,
        "helpersNearby": `Helpers Nearby`,
        "closeFollowStatus": `Close & Follow Status`,
        "matchingPartner": `We are matching you with a verified, friendly DigiSaathi partner.`,
        "statusPendingPartner": `Pending partner...`,
        "statusPartnerAssigned": `Partner assigned!`,
        "statusOnTheWay": `On The Way!`,
        "statusPartnerArrived": `Partner arrived!`,
        "statusServiceCompleted": `Service completed!`,
        "years": `Years`,
        "quickSweep": `Quick sweep`,
        "deepScrub": `Deep scrub`,
        "ecoWash": `Eco wash`,
        "homeAddressSlot": `Home (12, Ashoka Heights, Pune)`,
        "officeAddressSlot": `Office (Phase 3, Hinjewadi, Pune)`,
        "childrenAddressSlot": `Children's Home (Block B, Kothrud, Pune)`,
        "addNewAddressSlot": `Add New Address...`,
        "typeAddressPlaceholder": `Type your complete address here...`,
        "Hindi": `Hindi`,
        "Marathi": `Marathi`,
        "English": `English`,
        "Gujarati": `Gujarati`,
        "Bengali": `Bengali`,
        "Telugu": `Telugu`,
        "Tamil": `Tamil`, voice: 'en-IN', name: 'English', nativeName: 'English' },
  hi: {
        "gpsActive": `जीपीएस सक्रिय`,
        "gpsSearching": `जीपीएस खोज रहे हैं...`,
        "liveTracking": `लाइव ट्रैकिंग`,
        "simMovement": `चलने का अनुकरण`,
        "stopSimulation": `सिमुलेशन रोकें`,
        "shareWithFamily": `परिवार को भेजें`,
        "latitude": `अक्षांश`,
        "longitude": `देशांतर`,
        "speed": `गति`,
        "accuracy": `सटीकता`,
        "gpsActiveText": `लाइव जीपीएस ट्रैकिंग सक्रिय हो गई है। आपके डिवाइस का सिग्नल खोज रहे हैं...`,
        "gpsInactiveText": `लाइव ट्रैकिंग बंद कर दी गई है।`,
        "gpsErrorText": `जीपीएस सिग्नल कमजोर है। कृपया डिवाइस की अनुमति जांचें।`,
        "simActiveText": `पुणे में लाइव डिवाइस हलचल का अनुकरण शुरू हो गया है।`,
        "simInactiveText": `सिमुलेशन रोक दिया गया है।`,
        "currentLocSpoken": `आपका वर्तमान डिवाइस स्थान है`,
        "locationSharedSuccess": `लाइव स्थान सफलतापूर्वक आपके परिवार के साथ साझा किया गया!`,
        "cleaningCat": `सफाई सेवाएं`,
        "applianceCat": `उपकरण मरम्मत`,
        "medicineCat": `चिकित्सा सेवाएं`,
        "convenienceCat": `दैनिक सुविधा`,
        "safetyCat": `सुरक्षा और अलर्ट`,
        "Room Cleaning": `कमरे की सफाई`,
        "Room Cleaning_sub": `लिविंग रूम और बेडरूम में झाड़ू-पोंछा और साफ-सफाई।`,
        "Bathroom Cleaning": `बाथरूम की सफाई`,
        "Bathroom Cleaning_sub": `शौचालय और स्नानघर की गहरी सफाई और कीटाणुशोधन।`,
        "Kitchen Cleaning": `रसोई की सफाई`,
        "Kitchen Cleaning_sub": `गैस चूल्हे, काउंटरटॉप की सफाई और बर्तनों का रखरखाव।`,
        "Deep Home Cleaning": `घर की गहरी सफाई`,
        "Deep Home Cleaning_sub": `पूरे घर के हर कोने, खिड़कियों और कमरों की गहन सफाई।`,
        "Sofa Cleaning": `सोफा की सफाई`,
        "Sofa Cleaning_sub": `सोफे और कुर्सियों की वैक्यूमिंग और दाग-धब्बे हटाना।`,
        "Balcony Cleaning": `बालकनी की सफाई`,
        "Balcony Cleaning_sub": `बालकनी के फर्श की धुलाई और गमलों के आसपास की सफाई।`,
        "Floor Cleaning": `फर्श की सफाई`,
        "Floor Cleaning_sub": `फर्श को चमकाने और साफ रखने के लिए झाड़ू-पोंछा लगाना।`,
        "Stove Repair": `गैस चूल्हा मरम्मत`,
        "Stove Repair_sub": `रसोई के गैस चूल्हे में गैस रिसाव और बर्नर की खराबी ठीक करना।`,
        "Fan Repair": `पंखे की मरम्मत`,
        "Fan Repair_sub": `पंखे की आवाज, रेगुलेटर की समस्या और नया पंखा टांगना।`,
        "AC Repair": `एसी की मरम्मत`,
        "AC Repair_sub": `एसी की सर्विसिंग, फिल्टर सफाई और गैस रिसाव ठीक करना।`,
        "Refrigerator Repair": `फ्रिज की मरम्मत`,
        "Refrigerator Repair_sub": `फ्रिज में कूलिंग की कमी, आवाज आना और बिजली की खराबी दूर करना।`,
        "TV Repair": `टीवी की मरम्मत`,
        "TV Repair_sub": `टीवी स्क्रीन, आवाज की समस्या या सेटअप बॉक्स कनेक्शन ठीक करना।`,
        "Electrician": `इलेक्ट्रीशियन सेवा`,
        "Electrician_sub": `बिजली का शार्ट सर्किट ठीक करना, बोर्ड, स्विच और वायरिंग दुरुस्त करना।`,
        "Plumber": `प्लंबर सेवा`,
        "Plumber_sub": `टपकते नल ठीक करना, पाइप की रुकावट खोलना और पानी की टंकी दुरुस्त करना।`,
        "Water Purifier Service": `वॉटर प्यूरीफायर सर्विस`,
        "Water Purifier Service_sub": `आरओ (RO) फिल्टर बदलना, पानी की टंकी की सफाई और पानी की जांच।`,
        "Mobile Repair Assistance": `मोबाइल सहायता और मरम्मत`,
        "Mobile Repair Assistance_sub": `फोन की सेटिंग, ऐप डाउनलोड करने, स्क्रीन गार्ड या फोन ठीक करने में मदद।`,
        "Medicine Delivery": `दवाइयों की डिलीवरी`,
        "Medicine Delivery_sub": `डॉक्टर के पर्चे की दवाइयां सीधे आपके घर पर मंगवाना।`,
        "Doctor Appointment": `डॉक्टर से मिलने का समय`,
        "Doctor Appointment_sub": `पास के योग्य डॉक्टर से मिलने का समय बुक करना और प्रबंधन करना।`,
        "Video Doctor Consultation": `वीडियो कॉल पर डॉक्टर`,
        "Video Doctor Consultation_sub": `घर बैठे वीडियो कॉल द्वारा डॉक्टर से आमने-सामने परामर्श लेना।`,
        "Nurse Assistance": `नर्स की सहायता`,
        "Nurse Assistance_sub": `बीपी, शुगर जांचने, इंजेक्शन लगाने या पट्टी करने के लिए नर्स का घर पर आना।`,
        "Blood Test Booking": `रक्त जांच (ब्लड टेस्ट)`,
        "Blood Test Booking_sub": `घर पर आकर खून का सैंपल लेने और रिपोर्ट पहुंचाने की सुविधा।`,
        "Health Checkup": `पूर्ण स्वास्थ्य जांच`,
        "Health Checkup_sub": `घर से सैंपल लेने के साथ पूरे शरीर की जांच और रिपोर्ट की समीक्षा।`,
        "Physiotherapy": `फिजियोथेरेपी सेवा`,
        "Physiotherapy_sub": `जोड़ों के दर्द, कसरत और ऑपरेशन के बाद सुधार के लिए फिजियोथेरेपिस्ट की सेवाएं।`,
        "Ambulance Assistance": `आपातकालीन एम्बुलेंस`,
        "Ambulance Assistance_sub": `निकटतम अस्पताल जाने के लिए तुरंत एम्बुलेंस बुक करने में मदद।`,
        "Grocery Delivery": `किराना सामान की डिलीवरी`,
        "Grocery Delivery_sub": `ताजी सब्जियां, दूध, ब्रेड और राशन का सामान घर मंगवाना।`,
        "Cab Booking": `कैब और ऑटो बुकिंग`,
        "Cab Booking_sub": `खरीदारी, अस्पताल जाने या रिश्तेदारों से मिलने के लिए सुरक्षित गाड़ी बुक करना।`,
        "Bill Payment Help": `बिजली और गैस बिल`,
        "Bill Payment Help_sub": `बिजली, पानी, गैस या मोबाइल के बिल सुरक्षित रूप से ऑनलाइन भरना।`,
        "Document Assistance": `दस्तावेज़ सहायता`,
        "Document Assistance_sub": `जरूरी कागजात को व्यवस्थित करने, प्रिंट, स्कैन या फाइल करने में मदद।`,
        "Bank Visit Assistance": `बैंक जाने में सहायता`,
        "Bank Visit Assistance_sub": `पासबुक एंट्री या पैसे निकालने के लिए बैंक तक साथ जाने वाला सहायक।`,
        "Aadhaar/PAN Help": `आधार और पैन कार्ड सहायता`,
        "Aadhaar/PAN Help_sub": `आधार कार्ड अपडेट करने, पैन सुधारने या डिजिटल कॉपी डाउनलोड करने में मदद।`,
        "Companion Visit": `साथी का घर आना`,
        "Companion Visit_sub": `बातचीत करने, अखबार पढ़ने या पार्क में टहलने के लिए एक भरोसेमंद साथी।`,
        "Meal Delivery": `घर जैसा पौष्टिक भोजन`,
        "Meal Delivery_sub": `बुजुर्गों के लिए कम तेल-मसाले वाला, घर पर बना स्वच्छ भोजन पहुंचाना।`,
        "Emergency SOS": `आपातकालीन एसओएस बटन`,
        "Emergency SOS_sub": `मुसीबत के समय पुलिस, एम्बुलेंस और परिवार को तुरंत सूचित करने वाला बटन।`,
        "Scam Reporting": `धोखाधड़ी की रिपोर्ट`,
        "Scam Reporting_sub": `बैंक धोखाधड़ी, लॉटरी स्कैम या संदिग्ध संदेशों की पुलिस में शिकायत।`,
        "Trusted Contact Alert": `विश्वसनीय संपर्क सेटअप`,
        "Trusted Contact Alert_sub": `आपातकाल के लिए अपने बच्चों या करीबियों के फोन नंबर सेट करना।`,
        "Emergency Calling": `आपातकालीन हेल्पलाइन कॉल`,
        "Emergency Calling_sub": `सरकारी बुजुर्ग हेल्पलाइन, पुलिस या एम्बुलेंस को तुरंत कॉल करना।`,
        "Nearby Hospital Help": `आसपास के अस्पताल खोजना`,
        "Nearby Hospital Help_sub": `आपातकाल के लिए पास के बड़े अस्पतालों और क्लीनिकों का पता लगाना।`,
        "Live Location Sharing": `परिवार के साथ लोकेशन साझा करें`,
        "Live Location Sharing_sub": `आपकी सुरक्षा के लिए आपके चलने-फिरने की लाइव लोकेशन बच्चों के साथ साझा करना।`,
        "Safety Guidance": `धोखाधड़ी से बचाव के टिप्स`,
        "Safety Guidance_sub": `बैंक खाते, फोन और यूपीआई को सुरक्षित रखने की गाइड पढ़ना या सुनना।`,
        "Fraud Awareness": `नवीनतम धोखाधड़ी अलर्ट`,
        "Fraud Awareness_sub": `आपके इलाके में सक्रिय बिजली बिल, केवाईसी या लॉटरी के नए घोटालों की जानकारी।`,
        "alertInfoBanner": `क्या करना है यह जानने के लिए किसी भी अलर्ट पर टैप करें। अंदर बोलने वाले गाइड उपलब्ध हैं।`,
        "staySafe": `ऑनलाइन सुरक्षित रहें`,
        "learnToIdentify": `घोटालों को पहचानना और उनसे बचना सीखें`,
        "whatToDo": `क्या करें:`,
        "highSeverity": `उच्च चेतावनी`,
        "mediumSeverity": `मध्यम चेतावनी`,
        "selectHelpService": `सहायता सेवा चुनें`,
        "scheduledFor": `के लिए निर्धारित`,
        "at": `बजे`,
        "today": `आज`,
        "tomorrow": `कल`,
        "immediate": `तुरंत`,
        "addressLabel": `पता`,
        "ratingLabel": `रेटिंग`,
        "callBtn": `कॉल करें`,
        "resetBtn": `रीसेट`,
        "recentlyUsed": `हाल ही में उपयोग किए गए (1-टैप बुकिंग)`,
        "seniorsDeck": `वरिष्ठ नागरिक डेक`,
        "oneTapBook": `1-टैप बुकिंग`,
        "noMatchingFound": `कोई मेल खाने वाली सेवाएँ नहीं मिलीं।`,
        "trySearchingFor": `"AC", "सफाई", "डॉक्टर" या "SOS" खोजने का प्रयास करें।`,
        "availableNow": `अभी उपलब्ध`,
        "pricingPackages": `💰 मूल्य निर्धारण पैकेज`,
        "bookSlotOption": `⏱ स्लॉट बुक करने का विकल्प`,
        "selectDateDay": `तारीख और दिन चुनें`,
        "selectTimeSlot": `समय स्लॉट चुनें`,
        "languagesLabel": `भाषाएँ`,
        "addressSelection": `👤 पता चयन`,
        "totalPackagesCost": `कुल पैकेज लागत`,
        "confirmBooking": `बुकिंग की पुष्टि करें`,
        "optionsAvailable": `विकल्प उपलब्ध हैं`,
        "availableServices": `उपलब्ध सेवाएँ`,
        "closeBtn": `बंद करें`,
        "helpersNearby": `मददगार पास में हैं`,
        "closeFollowStatus": `बंद करें और स्थिति ट्रैक करें`,
        "matchingPartner": `हम आपको एक सत्यापित, मित्रवत डिजीसाथी पार्टनर से मिला रहे हैं।`,
        "statusPendingPartner": `पार्टनर की प्रतीक्षा है...`,
        "statusPartnerAssigned": `पार्टनर नियुक्त!`,
        "statusOnTheWay": `रास्ते में है!`,
        "statusPartnerArrived": `पार्टनर पहुँच गया!`,
        "statusServiceCompleted": `सेवा पूरी हुई!`,
        "years": `वर्ष`,
        "quickSweep": `त्वरित सफाई`,
        "deepScrub": `गहरी सफाई`,
        "ecoWash": `इको वॉश`,
        "homeAddressSlot": `घर (12, अशोक हाइट्स, पुणे)`,
        "officeAddressSlot": `कार्यालय (फेज 3, हिंजवड़ी, पुणे)`,
        "childrenAddressSlot": `बच्चों का घर (ब्लॉक बी, कोथरुड, पुणे)`,
        "addNewAddressSlot": `नया पता जोड़ें...`,
        "typeAddressPlaceholder": `अपना पूरा पता यहाँ लिखें...`,
        "Hindi": `हिंदी`,
        "Marathi": `मराठी`,
        "English": `अंग्रेजी`,
        "Gujarati": `गुजराती`,
        "Bengali": `बंगाली`,
        "Telugu": `तेलुगु`,
        "Tamil": `तमिल`, voice: 'hi-IN', name: 'Hindi', nativeName: 'हिंदी' },
  mr: {
        "gpsActive": `जीपीएस सक्रिय`,
        "gpsSearching": `जीपीएस शोधत आहे...`,
        "liveTracking": `लाईव्ह ट्रॅकिंग`,
        "simMovement": `चालण्याचा सराव`,
        "stopSimulation": `सराव थांबवा`,
        "shareWithFamily": `कुटुंबाला पाठवा`,
        "latitude": `अक्षांश`,
        "longitude": `रेखांश`,
        "speed": `वेग`,
        "accuracy": `अचूकता`,
        "gpsActiveText": `लाईव्ह जीपीएस ट्रॅकिंग सुरू झाले आहे. सिग्नल शोधत आहे...`,
        "gpsInactiveText": `लाईव्ह ट्रॅकिंग बंद केले आहे.`,
        "gpsErrorText": `जीपीएस सिग्नल कमकुवत आहे. कृपया परवानगी तपासा.`,
        "simActiveText": `पुण्यामध्ये चालण्याचा लाईव्ह सराव सुरू केला आहे.`,
        "simInactiveText": `सराव थांबवला आहे.`,
        "currentLocSpoken": `तुमचे चालू ठिकाण आहे`,
        "locationSharedSuccess": `तुमचे लाईव्ह स्थान कुटुंबासोबत यशस्वीरित्या शेअर केले आहे!`,
        "cleaningCat": `स्वच्छता सेवा`,
        "applianceCat": `घरगुती उपकरण दुरुस्ती`,
        "medicineCat": `वैद्यकीय सेवा`,
        "convenienceCat": `दैनिक सोयीसुविधा`,
        "safetyCat": `सुरक्षा आणि अलर्ट`,
        "Room Cleaning": `खोलीची स्वच्छता`,
        "Room Cleaning_sub": `लिव्हिंग रूम आणि बेडरुममध्ये झाडू मारणे, पुसणे आणि आवरणे।`,
        "Bathroom Cleaning": `बाथरूमची स्वच्छता`,
        "Bathroom Cleaning_sub": `शौचालय आणि स्नानगृहाची खोल स्वच्छता आणि जंतुनाशक फवारणी।`,
        "Kitchen Cleaning": `स्वयंपाकघराची स्वच्छता`,
        "Kitchen Cleaning_sub": `गॅस शेगडी, ओटा स्वच्छ करणे आणि भांडी व्यवस्थित लावणे।`,
        "Deep Home Cleaning": `घराची संपूर्ण स्वच्छता`,
        "Deep Home Cleaning_sub": `संपूर्ण घराच्या सर्व खोल्या, खिडक्या आणि कोनाकोपऱ्यांची सखोल स्वच्छता।`,
        "Sofa Cleaning": `सोफ्याची स्वच्छता`,
        "Sofa Cleaning_sub": `सोफा आणि खुर्च्या व्हॅक्यूम करणे आणि डाग घालवणे।`,
        "Balcony Cleaning": `बाल्कनीची स्वच्छता`,
        "Balcony Cleaning_sub": `बाल्कनीची फरशी धुणे आणि कुंड्यांच्या आसपासची स्वच्छता करणे।`,
        "Floor Cleaning": `फरशी पुसणे`,
        "Floor Cleaning_sub": `फरशी स्वच्छ आणि चमकदार ठेवण्यासाठी झाडून पुसून घेणे।`,
        "Stove Repair": `शेगडी दुरुस्ती`,
        "Stove Repair_sub": `स्वयंपाकघरातील गॅस शेगडीची गळती आणि बर्नरच्या समस्या सोडवणे।`,
        "Fan Repair": `पंखा दुरुस्ती`,
        "Fan Repair_sub": `आवाज करणाऱ्या पंख्याची दुरुस्ती, रेग्युलेटर दुरुस्त करणे आणि नवीन पंखा बसवणे।`,
        "AC Repair": `एसी दुरुस्ती`,
        "AC Repair_sub": `एसीची सर्व्हिसिंग, फिल्टर स्वच्छ करणे आणि गॅस गळती दुरुस्त करणे।`,
        "Refrigerator Repair": `फ्रिज दुरुस्ती`,
        "Refrigerator Repair_sub": `फ्रिजचे कुलिंग कमी होणे, आवाज येणे आणि विजेचे दोष दूर करणे।`,
        "TV Repair": `टीव्ही दुरुस्ती`,
        "TV Repair_sub": `टीव्ही स्क्रीन, आवाजाची समस्या किंवा सेटअप बॉक्सचे कनेक्शन दुरुस्त करणे।`,
        "Electrician": `इलेक्ट्रिशियन सेवा`,
        "Electrician_sub": `शॉर्ट सर्किट दुरुस्त करणे, बल्ब/स्विच बदलणे आणि वायरिंग तपासणे।`,
        "Plumber": `प्लंबर सेवा`,
        "Plumber_sub": `गळणारे नळ दुरुस्त करणे, तुंबलेल्या पाईप मोकळ्या करणे आणि पाण्याच्या टाक्या दुरुस्त करणे।`,
        "Water Purifier Service": `वॉटर प्युरिफायर सर्व्हिस`,
        "Water Purifier Service_sub": `आरओ (RO) फिल्टर बदलणे, पाण्याची टाकी स्वच्छ करणे आणि पाणी तपासणे।`,
        "Mobile Repair Assistance": `मोबाईल मदत आणि दुरुस्ती`,
        "Mobile Repair Assistance_sub": `फोन सेटिंग्ज, ॲप डाउनलोड करणे, स्क्रीन गार्ड किंवा मोबाईल दुरुस्तीत मदत।`,
        "Medicine Delivery": `औषध घरपोच सेवा`,
        "Medicine Delivery_sub": `डॉक्टरांनी लिहून दिलेली औषधे थेट तुमच्या दारापर्यंत मागवणे।`,
        "Doctor Appointment": `डॉक्टरांची भेट`,
        "Doctor Appointment_sub": `जवळच्या डॉक्टरांची भेट बुक करणे आणि नियोजित करणे।`,
        "Video Doctor Consultation": `व्हिडिओ कॉलवर डॉक्टर`,
        "Video Doctor Consultation_sub": `घरी बसून व्हिडिओ कॉलद्वारे डॉक्टरांशी समोरासमोर सल्लामसलत करणे।`,
        "Nurse Assistance": `नर्सची घरपोच सेवा`,
        "Nurse Assistance_sub": `बीपी, शुगर तपासण्यासाठी, इंजेक्शन देण्यासाठी किंवा मलमपट्टीसाठी नर्स घरी येणे।`,
        "Blood Test Booking": `रक्त तपासणी (ब्लड टेस्ट)`,
        "Blood Test Booking_sub": `घरी येऊन रक्ताचे नमुने गोळा करणे आणि अहवाल घरपोच देणे।`,
        "Health Checkup": `संपूर्ण आरोग्य तपासणी`,
        "Health Checkup_sub": `घरून नमुने गोळा करण्यासह संपूर्ण शरीराची तपासणी आणि अहवाल तपासणे।`,
        "Physiotherapy": `फिजियोथेरपी सेवा`,
        "Physiotherapy_sub": `सांधेदुखी, व्यायाम आणि शस्त्रक्रियेनंतरच्या रिकव्हरीसाठी फिजियोथेरपिस्ट घरी येणे।`,
        "Ambulance Assistance": `अॅम्ब्युलन्स सेवा`,
        "Ambulance Assistance_sub": `तातडीने रुग्णालयात जाण्यासाठी आपत्कालीन रुग्णवाहिका बुक करणे।`,
        "Grocery Delivery": `किराणा मालाची घरपोच सेवा`,
        "Grocery Delivery_sub": `ताजी भाजी, दूध, पाव आणि किराणा सामान घरपोच मागवणे।`,
        "Cab Booking": `कॅब आणि ऑटो बुकिंग`,
        "Cab Booking_sub": `खरेदी, रुग्णालय किंवा नातेवाईकांना भेटण्यासाठी सुरक्षित गाडी बुक करणे।`,
        "Bill Payment Help": `वीज आणि गॅस बिल भरणे`,
        "Bill Payment Help_sub": `वीज, पाणी, गॅस किंवा मोबाईलचे बिल सुरक्षितपणे ऑनलाईन भरणे।`,
        "Document Assistance": `कागदपत्र मदत`,
        "Document Assistance_sub": `महत्त्वाचे कागदपत्र व्यवस्थित ठेवणे, प्रिंट, स्कॅन किंवा फाईल करणे।`,
        "Bank Visit Assistance": `बँकेत जाण्यासाठी मदत`,
        "Bank Visit Assistance_sub": `पासबुक भरण्यासाठी किंवा पैसे काढण्यासाठी बँकेत सोबत जाणारा मदतनीस।`,
        "Aadhaar/PAN Help": `आधार आणि पॅन कार्ड मदत`,
        "Aadhaar/PAN Help_sub": `आधार कार्ड अपडेट करणे, पॅन सुधारणे किंवा डिजिटल कॉपी डाउनलोड करणे।`,
        "Companion Visit": `सोबत देण्यासाठी भेट`,
        "Companion Visit_sub": `गप्पा मारण्यासाठी, वृत्तपत्र वाचण्यासाठी किंवा बागेत फिरायला सोबत येणारा मित्र।`,
        "Meal Delivery": `घरगुती पौष्टिक जेवण`,
        "Meal Delivery_sub": `ज्येष्ठांसाठी कमी तेल-मसाल्याचे, घरगुती आणि सकस जेवण पोहोचवणे।`,
        "Emergency SOS": `आपत्कालीन एसओएस बटण`,
        "Emergency SOS_sub": `संकटकाळी पोलीस, रुग्णवाहिका आणि कुटुंबाला त्वरित संदेश देणारे बटण।`,
        "Scam Reporting": `सायबर फसवणुकीची तक्रार`,
        "Scam Reporting_sub": `बँक फसवणूक, लॉटरी स्कॅम किंवा संशयास्पद मेसेजची पोलिसांत तक्रार करणे।`,
        "Trusted Contact Alert": `विश्वासू संपर्क सेटअप`,
        "Trusted Contact Alert_sub": `आपत्कालीन वेळेसाठी मुले किंवा नातेवाईकांचे फोन नंबर सेट करणे।`,
        "Emergency Calling": `आपत्कालीन हेल्पलाईन कॉल`,
        "Emergency Calling_sub": `शासकीय ज्येष्ठ नागरिक हेल्पलाईन, पोलीस किंवा रुग्णवाहिकेला त्वरित फोन लावणे।`,
        "Nearby Hospital Help": `जवळची रुग्णालये शोधणे`,
        "Nearby Hospital Help_sub": `तात्काळ उपचारासाठी जवळच्या मोठ्या रुग्णालयांचा आणि क्लिनिकचा शोध घेणे।`,
        "Live Location Sharing": `लोकेशन कुटुंबासह शेअर करा`,
        "Live Location Sharing_sub": `तुमच्या सुरक्षिततेसाठी तुमची लाईव्ह लोकेशन मुलांसोबत शेअर करणे।`,
        "Safety Guidance": `फसवणुकीपासून बचावाचे उपाय`,
        "Safety Guidance_sub": `बँक खाते, फोन आणि यूपीआय सुरक्षित ठेवण्याबाबतचे मार्गदर्शन वाचणे किंवा ऐकणे।`,
        "Fraud Awareness": `नवीन फसवणुकीचे अलर्ट`,
        "Fraud Awareness_sub": `तुमच्या भागात वीज बिल, केवायसी किंवा लॉटरीच्या सुरू असलेल्या नवीन स्कॅमची माहिती मिळवणे।`,
        "alertInfoBanner": `काय करावे हे जाणून घेण्यासाठी कोणत्याही अलर्टवर टॅप करा. आत मार्गदर्शन ऐकण्यासाठी बटण उपलब्ध आहे.`,
        "staySafe": `ऑनलाइन सुरक्षित राहा`,
        "learnToIdentify": `फसवणूक ओळखायला आणि त्यापासून वाचायला शिका`,
        "whatToDo": `काय करावे:`,
        "highSeverity": `उच्च चेतावणी`,
        "mediumSeverity": `मध्यम चेतावणी`,
        "selectHelpService": `मदत सेवा निवडा`,
        "scheduledFor": `साठी नियोजित`,
        "at": `वाजता`,
        "today": `आज`,
        "tomorrow": `उद्या`,
        "immediate": `तातडीने`,
        "addressLabel": `पत्ता`,
        "ratingLabel": `रेटिंग`,
        "callBtn": `कॉल करा`,
        "resetBtn": `रिसेट`,
        "recentlyUsed": `नुकतेच वापरलेले (१-टॅप बुकिंग)`,
        "seniorsDeck": `ज्येष्ठ नागरिक डेक`,
        "oneTapBook": `१-टॅप बुकिंग`,
        "noMatchingFound": `एकही सेवा सापडली नाही.`,
        "trySearchingFor": `"AC", "स्वच्छता", "डॉक्टर" किंवा "SOS" शोधण्याचा प्रयत्न करा.`,
        "availableNow": `सध्या उपलब्ध`,
        "pricingPackages": `💰 पॅकेजचे दर`,
        "bookSlotOption": `⏱ वेळ निवडण्याचा पर्याय`,
        "selectDateDay": `तारीख आणि दिवस निवडा`,
        "selectTimeSlot": `वेळ निवडा`,
        "languagesLabel": `भाषा`,
        "addressSelection": `👤 पत्ता निवडा`,
        "totalPackagesCost": `एकूण पॅकेज किंमत`,
        "confirmBooking": `बुकिंग निश्चित करा`,
        "optionsAvailable": `पर्याय उपलब्ध आहेत`,
        "availableServices": `उपलब्ध सेवा`,
        "closeBtn": `बंद करा`,
        "helpersNearby": `मददगार जवळ आहेत`,
        "closeFollowStatus": `बंद करा आणि ट्रॅक करा`,
        "matchingPartner": `आम्ही तुम्हाला प्रमाणित, मित्रत्वाच्या डिजीसाथी पार्टनरशी जोडत आहोत.`,
        "statusPendingPartner": `पार्टनर शोधत आहे...`,
        "statusPartnerAssigned": `पार्टनर नियुक्त केला आहे!`,
        "statusOnTheWay": `पार्टनर येत आहे!`,
        "statusPartnerArrived": `पार्टनर पोहोचला आहे!`,
        "statusServiceCompleted": `सेवा यशस्वीरित्या पूर्ण झाली!`,
        "years": `वर्षे`,
        "quickSweep": `जलद स्वच्छता`,
        "deepScrub": `खोल स्वच्छता`,
        "ecoWash": `इको वॉश`,
        "homeAddressSlot": `घर (१२, अशोक हाइट्स, पुणे)`,
        "officeAddressSlot": `कार्यालय (फेज ३, हिंजवडी, पुणे)`,
        "childrenAddressSlot": `मुलांचे घर (ब्लॉक बी, कोथरूड, पुणे)`,
        "addNewAddressSlot": `नवीन पत्ता जोडा...`,
        "typeAddressPlaceholder": `तुमचा पूर्ण पत्ता येथे प्रविष्ट करा...`,
        "Hindi": `हिंदी`,
        "Marathi": `मराठी`,
        "English": `इंग्रजी`,
        "Gujarati": `गुजराती`,
        "Bengali": `बंगाली`,
        "Telugu": `तेलुगू`,
        "Tamil": `तमिळ`, voice: 'mr-IN', name: 'Marathi', nativeName: 'मराठी' },
  gu: {
        "gpsActive": `જીપીએસ સક્રિય`,
        "gpsSearching": `જીપીએસ શોધી રહ્યા છીએ...`,
        "liveTracking": `લાઈવ ટ્રેકિંગ`,
        "simMovement": `ચાલવાનું સિમ્યુલેશન`,
        "stopSimulation": `સિમ્યુલેશન બંધ કરો`,
        "shareWithFamily": `પરિવાર સાથે શેર કરો`,
        "latitude": `અક્ષાંશ`,
        "longitude": `રેખાંશ`,
        "speed": `ઝડપ`,
        "accuracy": `ચોકસાઈ`,
        "gpsActiveText": `લાઈવ જીપીએસ ટ્રેકિંગ સક્રિય થયું છે. સિગ્નલ શોધી રહ્યા છીએ...`,
        "gpsInactiveText": `લાઈવ ટ્રેકિંગ બંધ કરવામાં આવ્યું છે.`,
        "gpsErrorText": `જીપીએસ સિગ્નલ નબળું છે. કૃપા કરીને પરવાનગી તપાસો.`,
        "simActiveText": `પુણેમાં લાઈવ હલચલનું સિમ્યુલેશન શરૂ થયું છે.`,
        "simInactiveText": `સિમ્યુલેશન બંધ કરવામાં આવ્યું છે.`,
        "currentLocSpoken": `તમારું વર્તમાન સ્થાન છે`,
        "locationSharedSuccess": `લાઈવ સ્થાન સફળતાપૂર્વક પરિવાર સાથે શેર કરવામાં આવ્યું છે!`,
        "cleaningCat": `સફાઈ સેવાઓ`,
        "applianceCat": `ઉપકરણ સમારકામ`,
        "medicineCat": `તબીબી સેવાઓ`,
        "convenienceCat": `દૈનિક સુવિધા`,
        "safetyCat": `સુરક્ષા અને એલર્ટ`,
        "Room Cleaning": `રૂમની સફાઈ`,
        "Room Cleaning_sub": `લિવિંગ રૂમ અને બેડરૂમમાં કચરા-પોતા અને સાફ-સફાઈ.`,
        "Bathroom Cleaning": `બાથરૂમની સફાઈ`,
        "Bathroom Cleaning_sub": `ટોયલેટ અને બાથરૂમની ઊંડી સફાઈ અને જંતુનાશક સારવાર.`,
        "Kitchen Cleaning": `રસોડાની સફાઈ`,
        "Kitchen Cleaning_sub": `ગેસ સ્ટવ, પ્લેટફોર્મની સફાઈ અને વાસણોની ગોઠવણ.`,
        "Deep Home Cleaning": `ઘરની ઊંડી સફાઈ`,
        "Deep Home Cleaning_sub": `આખા ઘરના દરેક ખૂણા, બારીઓ અને રૂમોની સંપૂર્ણ સફાઈ.`,
        "Sofa Cleaning": `સોફાની સફાઈ`,
        "Sofa Cleaning_sub": `સોફા અને ખુરશીઓની વેક્યુમિંગ અને ડાઘા દૂર કરવા.`,
        "Balcony Cleaning": `બાલ્કનીની સફાઈ`,
        "Balcony Cleaning_sub": `બાલ્કનીના ફ્લોરનું ધોવાણ અને કુંડાઓની આસપાસની સફાઈ.`,
        "Floor Cleaning": `ફ્લોરની સફાઈ`,
        "Floor Cleaning_sub": `ફ્લોરને ચમકતો રાખવા માટે ઝાડુ અને પોતા મારવા.`,
        "Stove Repair": `ગેસ સ્ટવ રીપેર`,
        "Stove Repair_sub": `રસોડાના ગેસ સ્ટવનું લીકેજ અને બર્નરની સમસ્યાઓ સુધારવી.`,
        "Fan Repair": `પંખાનું સમારકામ`,
        "Fan Repair_sub": `અવાજ કરતા પંખાનું રીપેરીંગ અને નવો પંખો બેસાડવો.`,
        "AC Repair": `એસી સર્વિસિંગ`,
        "AC Repair_sub": `એસી ફિલ્ટરની સફાઈ અને ગેસ લીકેજની સમસ્યા સુધારવી.`,
        "Refrigerator Repair": `ફ્રિજ રીપેરીંગ`,
        "Refrigerator Repair_sub": `ફ્રિજમાં કુલિંગની સમસ્યા અને ઈલેક્ટ્રિક ફોલ્ટ સુધારવા.`,
        "TV Repair": `ટીવી રીપેરીંગ`,
        "TV Repair_sub": `ટીવી સ્ક્રીન, અવાજ અથવા સેટઅપ બોક્સ કનેક્શન સુધારવું.`,
        "Electrician": `ઈલેક્ટ્રિશિયન સેવા`,
        "Electrician_sub": `શોર્ટ સર્કિટ સુધારવી, સ્વિચ બદલવી અને વાયરિંગ ચેકઅપ.`,
        "Plumber": `પ્લમ્બર સેવા`,
        "Plumber_sub": `ટપકતા નળ સુધારવા અને પાઇપની લાઈનો સાફ કરવી.`,
        "Water Purifier Service": `વોટર પ્યુરિફાયર સર્વિસ`,
        "Water Purifier Service_sub": `આરઓ (RO) ફિલ્ટર બદલવા અને પાણીની ટાંકી સાફ કરવી.`,
        "Mobile Repair Assistance": `મોબાઇલ સહાય અને રીપેર`,
        "Mobile Repair Assistance_sub": `ફોન સેટિંગ્સ, એપ્લિકેશન ડાઉનલોડ કે ફોન સુધારવામાં મદદ.`,
        "Medicine Delivery": `દવાઓની ડિલિવરી`,
        "Medicine Delivery_sub": `ડોક્ટરની પ્રિસ્ક્રિપ્શનની દવાઓ સીધી ઘરે મંગાવો.`,
        "Doctor Appointment": `ડોક્ટરની મુલાકાત`,
        "Doctor Appointment_sub": `નજીકના સારા ડોક્ટરની મુલાકાત બુક કરવી અને મેનેજ કરવી.`,
        "Video Doctor Consultation": `વિડીયો કોલ પર ડોક્ટર`,
        "Video Doctor Consultation_sub": `ઘરે બેઠા વિડીયો કોલ દ્વારા ડોક્ટર સાથે લાઈવ વાતચીત.`,
        "Nurse Assistance": `નર્સની હોમ વિઝિટ`,
        "Nurse Assistance_sub": `બીપી, સુગર તપાસવા, ઇન્જેક્શન આપવા કે પાટાપીંડી માટે નર્સ હોમ વિઝિટ.`,
        "Blood Test Booking": `બ્લડ ટેસ્ટ બુકિંગ`,
        "Blood Test Booking_sub": `ઘરેથી લોહીના સેમ્પલ લેવા અને રીપોર્ટ પહોંચાડવાની સુવિધા.`,
        "Health Checkup": `સંપૂર્ણ હેલ્થ ચેકઅપ`,
        "Health Checkup_sub": `ઘરેથી સેમ્પલ કલેક્શન સાથે આખા શરીરની તપાસ અને રીપોર્ટ રિવ્યૂ.`,
        "Physiotherapy": `ફિઝીયોથેરાપી સેવા`,
        "Physiotherapy_sub": `સાંધાના દુખાવા અને કસરત માટે ફિઝીયોથેરાપિસ્ટની ઘર મુલાકાત.`,
        "Ambulance Assistance": `ઇમરજન્સી એમ્બ્યુલન્સ`,
        "Ambulance Assistance_sub": `તાત્કાલિક હોસ્પિટલ પહોંચવા માટે એમ્બ્યુલન્સ બુક કરવી.`,
        "Grocery Delivery": `કરિયાણાની ડિલિવરી`,
        "Grocery Delivery_sub": `તાજા શાકભાજી, દૂધ, બ્રેડ અને કરિયાણું ઘરે બેઠા મેળવો.`,
        "Cab Booking": `કેબ અને ઓટો બુકિંગ`,
        "Cab Booking_sub": `ખરીદી કે હોસ્પિટલ જવા માટે સુરક્ષિત ગાડી બુક કરવી.`,
        "Bill Payment Help": `બિલ ચુકવણીમાં મદદ`,
        "Bill Payment Help_sub": `લાઈટ બિલ, ગેસ બિલ કે મોબાઈલ રિચાર્જ ઓનલાઈન કરવા.`,
        "Document Assistance": `દસ્તાવેજ સહાય`,
        "Document Assistance_sub": `મહત્વના કાગળો ઓર્ગેનાઈઝ, પ્રિન્ટ કે સ્કેન કરવામાં મદદ.`,
        "Bank Visit Assistance": `બેંક મુલાકાતમાં મદદ`,
        "Bank Visit Assistance_sub": `પાસબુક એન્ટ્રી કે પૈસા ઉપાડવા માટે બેંક સુધી સાથે જનાર મિત્ર.`,
        "Aadhaar/PAN Help": `આધાર અને પાન કાર્ડ સહાય`,
        "Aadhaar/PAN Help_sub": `આધાર કાર્ડ અપડેટ કે ડિજિટલ કોપી ડાઉનલોડ કરવામાં મદદ.`,
        "Companion Visit": `સાથી મુલાકાત`,
        "Companion Visit_sub": `વાતો કરવા, છાપું વાંચવા કે બગીચામાં ફરવા માટે પ્રેમાળ સાથી.`,
        "Meal Delivery": `ઘર જેવું પૌષ્ટિક ભોજન`,
        "Meal Delivery_sub": `વડીલો માટે ઓછું તેલ-મસાલાવાળું સાત્વિક ભોજન પહોંચાડવું.`,
        "Emergency SOS": `ઇમરજન્સી એસઓએસ બટન`,
        "Emergency SOS_sub": `મુશ્કેલીના સમયે પોલીસ, એમ્બ્યુલન્સ અને ફેમિલીને તાત્કાલિક જાણ કરો.`,
        "Scam Reporting": `ફ્રોડની જાણ કરો`,
        "Scam Reporting_sub": `લૉટરી સ્કેમ કે શંકાસ્પદ મેસેજ સામે સાયબર ક્રાઇમમાં ફરિયાદ કરવી.`,
        "Trusted Contact Alert": `વિશ્વાસુ સંપર્ક સેટઅપ`,
        "Trusted Contact Alert_sub": `ઇમરજન્સી કોલ્સ માટે પરિવારના સભ્યોના નંબર સેટ કરવા.`,
        "Emergency Calling": `ઇમરજન્સી હેલ્પલાઇન કોલ`,
        "Emergency Calling_sub": `સરકારી વરિષ્ઠ નાગરિક હેલ્પલાઇન કે એમ્બ્યુલન્સને ડાયરેક્ટ કોલ.`,
        "Nearby Hospital Help": `નજીકની હોસ્પિટલ શોધવી`,
        "Nearby Hospital Help_sub": `ઇમરજન્સી સારવાર માટે નજીકની મોટી હોસ્પિટલો શોધવી.`,
        "Live Location Sharing": `ફેમિલી સાથે લોકેશન શેર કરો`,
        "Live Location Sharing_sub": `તમારી સલામતી માટે તમારી લાઈવ લોકેશન બાળકો સાથે શેર કરો.`,
        "Safety Guidance": `સ્કેમથી બચવાના ઉપાયો`,
        "Safety Guidance_sub": `બેંક એકાઉન્ટ અને યુપીઆઈ સુરક્ષિત રાખવાની ટિપ્સ વાંચવી કે સાંભળવી.`,
        "Fraud Awareness": `નવા ફ્રોડના એલર્ટ`,
        "Fraud Awareness_sub": `તમારા વિસ્તારમાં ચાલતા નવા કેવાયસી કે લાઈટ બિલના સ્કેમની માહિતી.`,
        "alertInfoBanner": `શું કરવું તે જાણવા માટે કોઈપણ એલર્ટ પર ટેપ કરો. અંદર માર્ગદર્શિકા સાંભળવાનો વિકલ્પ ઉપલબ્ધ છે.`,
        "staySafe": `ઓનલાઈન સુરક્ષિત રહો`,
        "learnToIdentify": `કૌભાંડો ઓળખતા અને તેનાથી બચતા શીખો`,
        "whatToDo": `શું કરવું:`,
        "highSeverity": `ઉચ્ચ ચેતવણી`,
        "mediumSeverity": `મધ્યમ ચેતવણી`,
        "selectHelpService": `મદદ સેવા પસંદ કરો`,
        "scheduledFor": `માટે નિર્ધારિત`,
        "at": `વાગ્યે`,
        "today": `આજે`,
        "tomorrow": `આવતીકાલે`,
        "immediate": `તરત જ`,
        "addressLabel": `સરનામું`,
        "ratingLabel": `રેટિંગ`,
        "callBtn": `કોલ કરો`,
        "resetBtn": `રીસેટ`,
        "recentlyUsed": `હમણાં જ વાપરેલી (૧-ટેપ બુકિંગ)`,
        "seniorsDeck": `વરિષ્ઠ નાગરિક ડેક`,
        "oneTapBook": `૧-ટેપ બુકિંગ`,
        "noMatchingFound": `કોઈ મેળ ખાતી સેવાઓ મળી નથી.`,
        "trySearchingFor": `"AC", "સફાઈ", "ડોક્ટર" અથવા "SOS" શોધવાનો પ્રયત્ન કરો.`,
        "availableNow": `અત્યારે ઉપલબ્ધ`,
        "pricingPackages": `💰 કિંમત પેકેજો`,
        "bookSlotOption": `⏱ સમય બુક કરવાનો વિકલ્પ`,
        "selectDateDay": `તારીખ અને દિવસ પસંદ કરો`,
        "selectTimeSlot": `સમય પસંદ કરો`,
        "languagesLabel": `ભાષાઓ`,
        "addressSelection": `👤 સરનામું પસંદ કરો`,
        "totalPackagesCost": `કુલ પેકેજ ખર્ચ`,
        "confirmBooking": `બુકિંગ કન્ફર્મ કરો`,
        "optionsAvailable": `વિકલ્પો ઉપલબ્ધ છે`,
        "availableServices": `ઉપલબ્ધ સેવાઓ`,
        "closeBtn": `બંધ કરો`,
        "helpersNearby": `મદદગારો નજીક છે`,
        "closeFollowStatus": `બંધ કરો અને સ્ટેટસ જુઓ`,
        "matchingPartner": `અમે તમને એક પ્રમાણિત, મૈત્રીપૂર્ણ ડિજીસાથી પાર્ટનર સાથે જોડી રહ્યા છીએ.`,
        "statusPendingPartner": `પાર્ટનર શોધાઈ રહ્યો છે...`,
        "statusPartnerAssigned": `પાર્ટનરની નિમણૂક થઈ ગઈ!`,
        "statusOnTheWay": `પાર્ટનર રસ્તામાં છે!`,
        "statusPartnerArrived": `પાર્ટનર આવી પહોંચ્યો!`,
        "statusServiceCompleted": `સેવા પૂર્ણ થઈ!`,
        "years": `વર્ષ`,
        "quickSweep": `ઝડપી સફાઈ`,
        "deepScrub": `ઊંડી સફાઈ`,
        "ecoWash": `ઇકો વોશ`,
        "homeAddressSlot": `ઘર (૧૨, અશોક હાઇટ્સ, પુણે)`,
        "officeAddressSlot": `ઓફિસ (ફેઝ ૩, હિંજવાડી, પુણે)`,
        "childrenAddressSlot": `બાળકોનું ઘર (બ્લોક બી, કોથરુડ, પુણે)`,
        "addNewAddressSlot": `નવું સરનામું ઉમેરો...`,
        "typeAddressPlaceholder": `તમારું આખું સરનામું અહીં લખો...`,
        "Hindi": `હિન્દી`,
        "Marathi": `મરાઠી`,
        "English": `અંગ્રેજી`,
        "Gujarati": `ગુજરાતી`,
        "Bengali": `બંગાળી`,
        "Telugu": `તેલુગુ`,
        "Tamil": `તમિલ`, voice: 'gu-IN', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  bn: {
        "gpsActive": `জিপিএস সক্রিয়`,
        "gpsSearching": `জিপিএস খোঁজা হচ্ছে...`,
        "liveTracking": `লাইভ ট্র্যাকিং`,
        "simMovement": `হাঁটার সিমুলেশন`,
        "stopSimulation": `সিমুলেশন বন্ধ করুন`,
        "shareWithFamily": `পরিবারে পাঠান`,
        "latitude": `অক্ষাংশ`,
        "longitude": `দ্রাঘিমাংশ`,
        "speed": `গতি`,
        "accuracy": `সঠি কতা`,
        "gpsActiveText": `লাইভ জিপিএস ট্র্যাকিং সক্রিয় হয়েছে। সংকেত খোঁজা হচ্ছে...`,
        "gpsInactiveText": `লাইভ ট্র্যাকিং নিষ্ক্রিয় করা হয়েছে।`,
        "gpsErrorText": `জিপিএস সংকেত দুর্বল। অনুগ্রহ করে অনুমতি যাচাই করুন।`,
        "simActiveText": `পুনেতে লাইভ মুভমেন্টের সিমুলেশন শুরু হয়েছে।`,
        "simInactiveText": `সিমুলেশন বন্ধ করা হয়েছে।`,
        "currentLocSpoken": `আপনার বর্তমান অবস্থান হলো`,
        "locationSharedSuccess": `লাইভ অবস্থান সফলভাবে পরিবারের সাথে ভাগ করা হয়েছে!`,
        "cleaningCat": `পরিষ্কারের পরিষেবা`,
        "applianceCat": `সরঞ্জাম মেরামত`,
        "medicineCat": `চিকিৎসা পরিষেবা`,
        "convenienceCat": `দৈনিক সুবিধা`,
        "safetyCat": `নিরাপত্তা ও সতর্কতা`,
        "Room Cleaning": `ঘর পরিষ্কার`,
        "Room Cleaning_sub": `শোবার ঘর এবং বসার ঘরে ঝাড়ু দেওয়া, মোছা এবং গুছিয়ে রাখা।`,
        "Bathroom Cleaning": `বাথরুম পরিষ্কার`,
        "Bathroom Cleaning_sub": `টয়লেট ও বাথরুমের গভীর পরিষ্কার এবং জীবাণুমুক্তকরণ।`,
        "Kitchen Cleaning": `রান্নাঘর পরিষ্কার`,
        "Kitchen Cleaning_sub": `গ্যাসের চুলা, স্ল্যাব পরিষ্কার এবং রান্নার বাসনপত্র গোছানো।`,
        "Deep Home Cleaning": `বাড়ি গভীর পরিষ্কার`,
        "Deep Home Cleaning_sub": `গোটা বাড়ির প্রতিটি কোণ, জানালা এবং ঘরের পুঙ্খানুপুঙ্খ পরিষ্কার।`,
        "Sofa Cleaning": `সোফা পরিষ্কার`,
        "Sofa Cleaning_sub": `সোফা এবং চেয়ারের ধুলো ঝাড়া এবং দাগ দূর করা।`,
        "Balcony Cleaning": `বারান্দা পরিষ্কার`,
        "Balcony Cleaning_sub": `বারান্দার মেঝে ধোয়া এবং টবের গাছের চারপাশ পরিষ্কার করা।`,
        "Floor Cleaning": `মেঝে পরিষ্কার`,
        "Floor Cleaning_sub": `মেঝে চকচকে এবং পরিষ্কার রাখার জন্য ঝাড়ু দেওয়া ও মোছা।`,
        "Stove Repair": `গ্যাস ওভেন মেরামত`,
        "Stove Repair_sub": `রান্নাঘরের গ্যাসের চুলা লিক বা বার্নার ঠিক করা।`,
        "Fan Repair": `পাখা মেরামত`,
        "Fan Repair_sub": `পাখার শব্দ ঠিক করা, রেগুলেটর বদলানো এবং নতুন পাখা লাগানো।`,
        "AC Repair": `এসি মেরামত`,
        "AC Repair_sub": `এসি ফিল্টার পরিষ্কার এবং গ্যাস লিক ঠিক করা।`,
        "Refrigerator Repair": `ফ্রিজ মেরামত`,
        "Refrigerator Repair_sub": `ফ্রিজের ঠাণ্ডা না হওয়া, শব্দ করা ও বৈদ্যুতিক ত্রুটি দূর করা।`,
        "TV Repair": `টিভি মেরামত`,
        "TV Repair_sub": `টিভির স্ক্রিন, সাউন্ড বা সেটআপ বক্সের সংযোগ ঠিক করা।`,
        "Electrician": `ইলেকট্রিশিয়ান পরিষেবা`,
        "Electrician_sub": `শর্ট সার্কিট ঠিক করা, বাল্ব/সুইচ বদলানো এবং ওয়ারিং চেকআপ।`,
        "Plumber": `প্লাম্বার পরিষেবা`,
        "Plumber_sub": `কল লিক করা ঠিক করা, পাইপের জ্যাম পরিষ্কার করা এবং জলের ট্যাঙ্ক মেরামত।`,
        "Water Purifier Service": `ওয়াটার পিউরিফায়ার সার্ভিস`,
        "Water Purifier Service_sub": `আরও (RO) ফিল্টার পরিবর্তন করা এবং জলের ট্যাঙ্ক পরিষ্কার করা।`,
        "Mobile Repair Assistance": `মোবাইল সহায়তা ও মেরামত`,
        "Mobile Repair Assistance_sub": `ফোন সেটিং, অ্যাপ ডাউনলোড, স্ক্রিন গার্ড বা ফোন মেরামতে সাহায্য।`,
        "Medicine Delivery": `ওষুধ সরবরাহ`,
        "Medicine Delivery_sub": `ডাক্তারের প্রেসক্রিপশনের ওষুধ সরাসরি আপনার বাড়িতে পৌঁছে দেওয়া।`,
        "Doctor Appointment": `ডাক্তারের অ্যাপয়েন্টমেন্ট`,
        "Doctor Appointment_sub": `নিকটবর্তী ভালো ডাক্তারের সাথে সরাসরি অ্যাপয়েন্টমেন্ট বুকিং।`,
        "Video Doctor Consultation": `ভিডিও কলে ডাক্তার`,
        "Video Doctor Consultation_sub": `বাড়ি বসেই ভিডিও কলের মাধ্যমে ডাক্তারের সাথে সরাসরি পরামর্শ।`,
        "Nurse Assistance": `নার্সের হোম ভিজিট`,
        "Nurse Assistance_sub": `বিপি, সুগার পরীক্ষা, ইনজেকশন দেওয়া বা ড্রেসিংয়ের জন্য নার্স সেবা।`,
        "Blood Test Booking": `রক্ত পরীক্ষা বুকিং`,
        "Blood Test Booking_sub": `বাড়ি এসে রক্তের নমুনা সংগ্রহ এবং রিপোর্ট পৌঁছে দেওয়ার সুবিধা।`,
        "Health Checkup": `সম্পূর্ণ স্বাস্থ্য পরীক্ষা`,
        "Health Checkup_sub": `বাড়ি থেকে রক্তের নমুনা সংগ্রহ করে শরীরের সামগ্রিক পরীক্ষা ও রিপোর্ট।`,
        "Physiotherapy": `ফিজিওথেরাপি পরিষেবা`,
        "Physiotherapy_sub": `গাঁটের ব্যথা, ব্যায়াম এবং অপারেশনের পরবর্তী সুস্থতার জন্য ফিজিওথেরাপিস্টের সেবা।`,
        "Ambulance Assistance": `জরুরী অ্যাম্বুলেন্স`,
        "Ambulance Assistance_sub": `জরুরী হাসপাতালে যাওয়ার জন্য দ্রুত অ্যাম্বুলেন্স বুকিং।`,
        "Grocery Delivery": `মুদিখানার জিনিসপত্র`,
        "Grocery Delivery_sub": `তাজা শাকসবজি, দুধ, রুটি এবং চাল-ডাল ইত্যাদি ঘরে পৌঁছে দেওয়া।`,
        "Cab Booking": `ক্যাব ও অটো বুকিং`,
        "Cab Booking_sub": `কেনাকাটা, হাসপাতাল বা আত্মীয়দের বাড়ি যাওয়ার জন্য নিরাপদ গাড়ি বুকিং।`,
        "Bill Payment Help": `বিল পরিশোধে সহায়তা`,
        "Bill Payment Help_sub": `অনলাইনে বিদ্যুৎ, গ্যাস, জল বা মোবাইলের বিল নিরাপদে জমা দেওয়া।`,
        "Document Assistance": `নথিপত্র সহায়তা`,
        "Document Assistance_sub": `প্রয়োজনীয় সরকারি কাগজ গোছানো, প্রিন্ট বা স্ক্যান করতে সাহায্য।`,
        "Bank Visit Assistance": `ব্যাঙ্ক যাওয়ার সাহায্যকারী`,
        "Bank Visit Assistance_sub": `পাসবই আপডেট বা টাকা তুলতে ব্যাঙ্কে সাথে যাওয়ার জন্য একজন সঙ্গী।`,
        "Aadhaar/PAN Help": `আধার ও প্যান কার্ড সহায়তা`,
        "Aadhaar/PAN Help_sub": `আধার আপডেট বা প্যান কার্ড সংশোধন ও ডিজিটাল কপি ডাউনলোড।`,
        "Companion Visit": `সঙ্গী হোম ভিজিট`,
        "Companion Visit_sub": `গল্প করার জন্য, খবরের কাগজ পড়ার জন্য বা পার্কে হাঁটতে যাওয়ার নির্ভরযোগ্য সঙ্গী।`,
        "Meal Delivery": `বাড়ির মতো পুষ্টিকর খাবার`,
        "Meal Delivery_sub": `প্রবীণদের জন্য কম তেল-মশলার স্বাস্থ্যকর ঘরোয়া খাবার সরবরাহ।`,
        "Emergency SOS": `জরুরী এসওএস বোতাম`,
        "Emergency SOS_sub": `বিপদের সময় পুলিশ, অ্যাম্বুলেন্স এবং পরিবারকে দ্রুত সতর্কবার্তা পাঠানো।`,
        "Scam Reporting": `প্রতারণা রিপোর্ট`,
        "Scam Reporting_sub": `ভুয়ো লটারি বা ব্যাঙ্ক জালিয়াতির বিরুদ্ধে পুলিশে অভিযোগ জানানো।`,
        "Trusted Contact Alert": `বিশ্বস্ত নম্বর সেটআপ`,
        "Trusted Contact Alert_sub": `জরুরী প্রয়োজনের জন্য পরিবারের প্রিয়জনদের ফোন নম্বর সেট করে রাখা।`,
        "Emergency Calling": `জরুরী হেল্পলাইন কল`,
        "Emergency Calling_sub": `সরকারি বয়স্ক হেল্পলাইন, পুলিশ বা অ্যাম্বুলেন্সে সরাসরি কল করা।`,
        "Nearby Hospital Help": `কাছের হাসপাতাল খোঁজা`,
        "Nearby Hospital Help_sub": `জরুরী চিকিৎসার জন্য নিকটবর্তী হাসপাতাল ও নার্সিং হোম খোঁজা।`,
        "Live Location Sharing": `পরিবারের সাথে অবস্থান শেয়ার`,
        "Live Location Sharing_sub": `আপনার নিরাপত্তার জন্য আপনার লাইভ অবস্থান সন্তানদের সাথে শেয়ার করুন।`,
        "Safety Guidance": `জালিয়াতি থেকে বাঁচার উপায়`,
        "Safety Guidance_sub": `ব্যাঙ্ক ও ইউপিআই নিরাপদে ব্যবহারের নির্দেশিকা পড়া বা শোনা।`,
        "Fraud Awareness": `নতুন জালিয়াতির সতর্কতা`,
        "Fraud Awareness_sub": `আপনার এলাকায় চলা নতুন বিদ্যুৎ বিল বা কেওয়াইসি স্ক্যামের খবর।`,
        "alertInfoBanner": `কী করতে হবে তা জানতে যেকোনো সতর্কবার্তায় ট্যাপ করুন। ভেতরে শোনার জন্য গাইড দেওয়া রয়েছে।`,
        "staySafe": `অনলাইন নিরাপদ থাকুন`,
        "learnToIdentify": `প্রতারণা সনাক্ত করতে এবং এড়াতে শিখুন`,
        "whatToDo": `করণীয়:`,
        "highSeverity": `উচ্চ সতর্কতা`,
        "mediumSeverity": `মাঝারি সতর্কতা`,
        "selectHelpService": `সহায়তা পরিষেবা নির্বাচন করুন`,
        "scheduledFor": `এর জন্য নির্ধারিত`,
        "at": `টায়`,
        "today": `আজ`,
        "tomorrow": `আগামীকাল`,
        "immediate": `অবিলম্বে`,
        "addressLabel": `ঠিকানা`,
        "ratingLabel": `রেটিং`,
        "callBtn": `কল করুন`,
        "resetBtn": `রিসেট`,
        "recentlyUsed": `সাম্প্রতিক ব্যবহৃত (১-ট্যাপ বুকিং)`,
        "seniorsDeck": `প্রবীণ নাগরিক ডেক`,
        "oneTapBook": `১-ট্যাপ বুকিং`,
        "noMatchingFound": `কোনো মিল পরিষেবা পাওয়া যায়নি।`,
        "trySearchingFor": `"AC", "পরিষ্কার", "ডাক্তার" বা "SOS" খোঁজার চেষ্টা করুন।`,
        "availableNow": `এখন উপলব্ধ`,
        "pricingPackages": `💰 মূল্য নির্ধারণ প্যাকেজ`,
        "bookSlotOption": `⏱ স্লট বুকিং অপশন`,
        "selectDateDay": `তারিখ এবং দিন নির্বাচন করুন`,
        "selectTimeSlot": `সময় নির্বাচন করুন`,
        "languagesLabel": `ভাষা সমূহ`,
        "addressSelection": `👤 ঠিকানা নির্বাচন`,
        "totalPackagesCost": `মোট প্যাকেজ খরচ`,
        "confirmBooking": `বুকিং নিশ্চিত করুন`,
        "optionsAvailable": `বিকল্প উপলব্ধ আছে`,
        "availableServices": `উপলব্ধ পরিষেবা সমূহ`,
        "closeBtn": `বন্ধ করুন`,
        "helpersNearby": `সাহায্যকারীরা কাছেই আছেন`,
        "closeFollowStatus": `বন্ধ করুন এবং ট্র্যাক করুন`,
        "matchingPartner": `আমরা আপনাকে একজন যাচাইকৃত, বন্ধুত্বপূর্ণ ডিজি সাথী পার্টনারের সাথে মিলিয়ে দিচ্ছি।`,
        "statusPendingPartner": `পার্টনার খোঁজা হচ্ছে...`,
        "statusPartnerAssigned": `পার্টনার নিযুক্ত হয়েছে!`,
        "statusOnTheWay": `পার্টনার রাস্তায় আছে!`,
        "statusPartnerArrived": `পার্টনার পৌঁছে গেছেন!`,
        "statusServiceCompleted": `পরিষেবা সফলভাবে সম্পূর্ণ হয়েছে!`,
        "years": `বছর`,
        "quickSweep": `দ্রুত পরিষ্কার`,
        "deepScrub": `গভীর পরিষ্কার`,
        "ecoWash": `ইকো ওয়াশ`,
        "homeAddressSlot": `বাড়ি (১২, অশোকা হাইটস, পুনে)`,
        "officeAddressSlot": `অফিস (ফেজ ৩, হিঞ্জেওয়াড়ি, পুনে)`,
        "childrenAddressSlot": `বাচ্চাদের বাড়ি (ব্লক বি, কোথরূড, পুনে)`,
        "addNewAddressSlot": `নতুন ঠিকানা যোগ করুন...`,
        "typeAddressPlaceholder": `আপনার সম্পূর্ণ ঠিকানা এখানে লিখুন...`,
        "Hindi": `হিন্দি`,
        "Marathi": `মরাঠি`,
        "English": `ইংরেজি`,
        "Gujarati": `গুজরাটি`,
        "Bengali": `বাংলা`,
        "Telugu": `তেলুগু`,
        "Tamil": `তামিল`, voice: 'bn-IN', name: 'Bengali', nativeName: 'বাংলা' },
  ta: {
        "gpsActive": `ஜிபிஎஸ் செயல்படுகிறது`,
        "gpsSearching": `ஜிபிஎஸ் தேடுகிறது...`,
        "liveTracking": `நேரடி கண்காணிப்பு`,
        "simMovement": `நடை உருவகப்படுத்துதல்`,
        "stopSimulation": `நிறுத்துக`,
        "shareWithFamily": `குடும்பத்தினருக்கு அனுப்பு`,
        "latitude": `அட்சரேகை`,
        "longitude": `தீர்க்கரேகை`,
        "speed": `வேகம்`,
        "accuracy": `துல்லியம்`,
        "gpsActiveText": `நேரடி ஜிபிஎஸ் கண்காணிப்பு செயல்படுத்தப்பட்டது. சிக்னலை தேடுகிறது...`,
        "gpsInactiveText": `நேரடி கண்காணிப்பு நிறுத்தப்பட்டது.`,
        "gpsErrorText": `ஜிபிஎஸ் சிக்னல் பலவீனமாக உள்ளது. அனுமதியை சரிபார்க்கவும்.`,
        "simActiveText": `புனேயில் நேரடி நடமாட்ட உருவகப்படுத்துதல் தொடங்கப்பட்டது.`,
        "simInactiveText": `உருவகப்படுத்துதல் நிறுத்தப்பட்டது.`,
        "currentLocSpoken": `உங்களது தற்போதைய இருப்பிடம்`,
        "locationSharedSuccess": `நேரடி இருப்பிடம் குடும்பத்தினருடன் வெற்றிகரமாக பகிரப்பட்டது!`,
        "cleaningCat": `சுத்தம் செய்தல்`,
        "applianceCat": `பழுதுபார்த்தல்`,
        "medicineCat": `மருத்துவ சேவைகள்`,
        "convenienceCat": `தினசரி தேவைகள்`,
        "safetyCat": `பாதுகாப்பு & விழிப்பூட்டல்கள்`,
        "Room Cleaning": `அறை சுத்தம் செய்தல்`,
        "Room Cleaning_sub": `வரவேற்பறை மற்றும் படுக்கை அறைகளை ஒட்டடை அடித்து, கூட்டி துடைத்தல்.`,
        "Bathroom Cleaning": `கழிவறை சுத்தம் செய்தல்`,
        "Bathroom Cleaning_sub": `கழிவறைகளை கிருமிநாசினி கொண்டு ஆழமாக சுத்தம் செய்தல்.`,
        "Kitchen Cleaning": `சமையலறை சுத்தம் செய்தல்`,
        "Kitchen Cleaning_sub": `அடுப்பு, மேடை மற்றும் சமையல் பாத்திரங்களை சுத்தம் செய்தல்.`,
        "Deep Home Cleaning": `வீடு முழுவதும் சுத்தம்`,
        "Deep Home Cleaning_sub": `வீட்டின் அனைத்து அறைகள், ஜன்னல்கள் மற்றும் மூலைகளை சுத்தம் செய்தல்.`,
        "Sofa Cleaning": `சோபா சுத்தம் செய்தல்`,
        "Sofa Cleaning_sub": `சோபா மற்றும் நாற்காலிகளின் தூசிகளை அகற்றி கறைகளை போக்குதல்.`,
        "Balcony Cleaning": `பால்கனி சுத்தம் செய்தல்`,
        "Balcony Cleaning_sub": `பால்கனி தரையை கழுவி, செடிகள் உள்ள இடத்தை சுத்தம் செய்தல்.`,
        "Floor Cleaning": `தரை சுத்தம் செய்தல்`,
        "Floor Cleaning_sub": `தரையை கூட்டி, துடைத்து பளபளப்பாக வைத்திருத்தல்.`,
        "Stove Repair": `அடுப்பு பழுதுபார்த்தல்`,
        "Stove Repair_sub": `கேஸ் கசிவு, பர்னர் அடைப்பு மற்றும் அடுப்பு பழுதுகளை நீக்குதல்.`,
        "Fan Repair": `மின்விசிறி பழுதுநீக்கம்`,
        "Fan Repair_sub": `மின்விசிறியின் சத்தம், ரெகுலேட்டர் பழுது மற்றும் புதிய மின்விசிறி மாட்டுதல்.`,
        "AC Repair": `ஏசி பழுதுநீக்கம்`,
        "AC Repair_sub": `ஏசி பில்டர்களை சுத்தம் செய்து கேஸ் கசிவை பழுதுபார்த்தல்.`,
        "Refrigerator Repair": `பிரிட்ஜ் பழுதுநீக்கம்`,
        "Refrigerator Repair_sub": `பிரிட்ஜ் குளிர்ச்சி குறைபாடு, சத்தம் மற்றும் மின்சார பழுதுகளை சரிசெய்தல்.`,
        "TV Repair": `டிவி பழுதுநீக்கம்`,
        "TV Repair_sub": `டிவி திரை, சத்தம் அல்லது செட்டப் பாக்ஸ் இணைப்பை சரிசெய்தல்.`,
        "Electrician": `மின்சார உதவியாளர்`,
        "Electrician_sub": `மின்சார ஷார்ட் சர்க்யூட் சரிசெய்தல், பல்பு/சுவிட்ச் மாற்றுதல்.`,
        "Plumber": `குழாய் பழுதுநீக்குபவர்`,
        "Plumber_sub": `நீர் கசியும் குழாய்களை சரிசெய்தல், அடைப்புகளை நீக்குதல்.`,
        "Water Purifier Service": `வாட்டர் பியூரிபையர் சேவை`,
        "Water Purifier Service_sub": `ஆர்ஓ (RO) பில்டர்களை மாற்றி, தண்ணீர் தொட்டியை சுத்தம் செய்தல்.`,
        "Mobile Repair Assistance": `மொபைல் பழுது மற்றும் உதவி`,
        "Mobile Repair Assistance_sub": `மொபைல் போன் அமைப்புகள், ஆப் டவுன்லோடு மற்றும் பழுது சரிசெய்தல்.`,
        "Medicine Delivery": `மருந்து விநியோகம்`,
        "Medicine Delivery_sub": `மருத்துவர் பரிந்துரைத்த மருந்துகளை உங்கள் வீட்டிற்கே வரவழைத்தல்.`,
        "Doctor Appointment": `மருத்துவர் முன்பதிவு`,
        "Doctor Appointment_sub": `அருகிலுள்ள சிறந்த மருத்துவரை பார்க்க நேர முன்பதிவு செய்தல்.`,
        "Video Doctor Consultation": `வீடியோ கால் மருத்துவர்`,
        "Video Doctor Consultation_sub": `வீட்டிலிருந்தபடியே வீடியோ கால் மூலம் மருத்துவரிடம் ஆலோசனை பெறுதல்.`,
        "Nurse Assistance": `செவிலியர் வீட்டு சேவை`,
        "Nurse Assistance_sub": `பிபி, சர்க்கரை அளவு சோதிக்க, ஊசி போட செவிலியர் வீட்டு சேவை.`,
        "Blood Test Booking": `இரத்த பரிசோதனை`,
        "Blood Test Booking_sub": `வீட்டிற்கே வந்து இரத்த மாதிரிகள் எடுத்து முடிவுகளை தருதல்.`,
        "Health Checkup": `முழு உடல் பரிசோதனை`,
        "Health Checkup_sub": `வீட்டிலிருந்தே மாதிரி சேகரிப்புடன் முழு உடல் பரிசோதனை தொகுப்பு.`,
        "Physiotherapy": `பயிற்சி சிகிச்சை`,
        "Physiotherapy_sub": `மூட்டு வலி, உடற்பயிற்சிகளுக்கு பிசியோதெரபிஸ்ட் வீட்டு சேவை.`,
        "Ambulance Assistance": `அவசர ஆம்புலன்ஸ்`,
        "Ambulance Assistance_sub": `அவசரமாக மருத்துவமனை செல்ல உடனடியாக ஆம்புலன்ஸ் முன்பதிவு.`,
        "Grocery Delivery": `மளிகைப் பொருட்கள்`,
        "Grocery Delivery_sub": `புதிய காய்கறிகள், பால், ரொட்டி மற்றும் மளிகைப் பொருட்களை வீட்டுக்கே தருதல்.`,
        "Cab Booking": `டாக்சி மற்றும் ஆட்டோ`,
        "Cab Booking_sub": `வெளிவேலைகள், மருத்துவமனை செல்ல பாதுகாப்பான கார்/ஆட்டோ முன்பதிவு.`,
        "Bill Payment Help": `கட்டணங்கள் செலுத்துதல்`,
        "Bill Payment Help_sub": `மின்சாரம், தண்ணீர், மொபைல் கட்டணங்களை ஆன்லைனில் பாதுகாப்பாக செலுத்துதல்.`,
        "Document Assistance": `ஆவணங்கள் உதவி`,
        "Document Assistance_sub": `முக்கிய அரசாங்க ஆவணங்களை ஒழுங்குபடுத்த, பிரின்ட் செய்ய உதவி.`,
        "Bank Visit Assistance": `வங்கி செல்ல உதவியாளர்`,
        "Bank Visit Assistance_sub": `பணம் எடுக்க, புத்தக பதிவு செய்ய வங்கிக்கு துணையாக வருபவர்.`,
        "Aadhaar/PAN Help": `ஆதார் & பான் கார்டு உதவி`,
        "Aadhaar/PAN Help_sub": `ஆதார் திருத்தங்கள் அல்லது பான் கார்டு டிஜிட்டல் நகல் பதிவிறக்கம்.`,
        "Companion Visit": `துணைக்கு நண்பர்`,
        "Companion Visit_sub": `பேசுவதற்கும், செய்தித்தாள் வாசிப்பதற்கும் ஒரு நம்பிக்கையான துணை.`,
        "Meal Delivery": `சத்தான வீட்டு உணவு`,
        "Meal Delivery_sub": `முதியோர்களுக்கான குறைந்த எண்ணெய்-காரமுள்ள சத்தான வீட்டு உணவு.`,
        "Emergency SOS": `அவசர எஸ்ஓஎஸ் பொத்தான்`,
        "Emergency SOS_sub": `ஆபத்து காலங்களில் போலீஸ், ஆம்புலன்ஸ் மற்றும் குடும்பத்திற்கு தகவல் அனுப்பும் பொத்தான்.`,
        "Scam Reporting": `மோசடி புகார்`,
        "Scam Reporting_sub": `வங்கி மோசடிகள், போலி லாட்டரி அழைப்புகள் குறித்து போலீசில் புகார் செய்தல்.`,
        "Trusted Contact Alert": `நம்பிக்கை எண்கள் அமைப்பு`,
        "Trusted Contact Alert_sub": `அவசர கால தொடர்புகளுக்கு பிள்ளைகளின் எண்களை சேமித்தல்.`,
        "Emergency Calling": `அவசர ஹெல்ப்லைன் அழைப்பு`,
        "Emergency Calling_sub": `அரசு முதியோர் ஹெல்ப்லைன் அல்லது போலீசாருக்கு உடனடியாக அழைத்தல்.`,
        "Nearby Hospital Help": `அருகிலுள்ள மருத்துவமனைகள்`,
        "Nearby Hospital Help_sub": `அவசர சிகிச்சைக்கு அருகிலுள்ள மருத்துவமனைகளை கண்டறிதல்.`,
        "Live Location Sharing": `இருப்பிடத்தை பகிர்தல்`,
        "Live Location Sharing_sub": `பாதுகாப்பிற்காக உங்கள் தற்போதைய நடமாட்ட இருப்பிடத்தை பிள்ளைகளுக்கு பகிர்தல்.`,
        "Safety Guidance": `மோசடி தடுப்பு வழிகள்`,
        "Safety Guidance_sub": `வங்கி கணக்கு, போன்களை பாதுகாப்பாக வைப்பதற்கான வழிகளை படித்தல்/கேட்டல்.`,
        "Fraud Awareness": `புதிய மோசடி எச்சரிக்கைகள்`,
        "Fraud Awareness_sub": `உங்கள் பகுதியில் நடக்கும் புதிய மின்சார பில், கேஒய்சி மோசடி எச்சரிக்கைகள்.`,
        "alertInfoBanner": `என்ன செய்ய வேண்டும் என்பதை அறிய ஏதேனும் ஒரு விழிப்பூட்டலைத் தட்டவும். உள்ளே வழிகாட்டி குரல் உள்ளது.`,
        "staySafe": `ஆன்லைனில் பாதுகாப்பாக இருங்கள்`,
        "learnToIdentify": `மோசடிகளைக் கண்டறிந்து தவிர்க்கக் கற்றுக்கொள்ளுங்கள்`,
        "whatToDo": `செய்ய வேண்டியவை:`,
        "highSeverity": `உயர் விழிப்பூட்டல்`,
        "mediumSeverity": `நடுத்தர விழிப்பூட்டல்`,
        "selectHelpService": `உதவி சேவையைத் தேர்ந்தெடுக்கவும்`,
        "scheduledFor": `திட்டமிடப்பட்டுள்ளது`,
        "at": `மணிக்கு`,
        "today": `இன்று`,
        "tomorrow": `நாளை`,
        "immediate": `உடனடியாக`,
        "addressLabel": `முகவரி`,
        "ratingLabel": `மதிப்பீடு`,
        "callBtn": `அழைக்க`,
        "resetBtn": `மீட்டமை`,
        "recentlyUsed": `சமீபத்தில் பயன்படுத்தியவை (1-தட்டல் முன்பதிவு)`,
        "seniorsDeck": `முதியோர் பகுதி`,
        "oneTapBook": `1-தட்டல் முன்பதிவு`,
        "noMatchingFound": `பொருந்தும் சேவைகள் எதுவும் இல்லை.`,
        "trySearchingFor": `"AC", "சுத்தம்", "மருத்துவர்" அல்லது "SOS" தேட முயற்சிக்கவும்.`,
        "availableNow": `இப்போது கிடைக்கிறது`,
        "pricingPackages": `💰 கட்டணத் திட்டங்கள்`,
        "bookSlotOption": `⏱ நேரத் தேர்வு`,
        "selectDateDay": `தேதி மற்றும் கிழமையைத் தேர்ந்தெடுக்கவும்`,
        "selectTimeSlot": `நேரத்தைத் தேர்ந்தெடுக்கவும்`,
        "languagesLabel": `மொழிகள்`,
        "addressSelection": `👤 முகவரித் தேர்வு`,
        "totalPackagesCost": `மொத்த கட்டணம்`,
        "confirmBooking": `முன்பதிவை உறுதி செய்`,
        "optionsAvailable": `விருப்பங்கள் உள்ளன`,
        "availableServices": `கிடைக்கும் சேவைகள்`,
        "closeBtn": `மூடு`,
        "helpersNearby": `உதவியாளர்கள் அருகில் உள்ளனர்`,
        "closeFollowStatus": `மூடிவிட்டு நிலையைப் பின்தொடரவும்`,
        "matchingPartner": `சரிபார்க்கப்பட்ட, நட்புமிக்க டிஜிசாதி பார்ட்னருடன் உங்களை இணைக்கிறோம்.`,
        "statusPendingPartner": `பார்ட்னரைத் தேடுகிறது...`,
        "statusPartnerAssigned": `பார்ட்னர் நியமிக்கப்பட்டுள்ளார்!`,
        "statusOnTheWay": `பார்ட்னர் வந்து கொண்டிருக்கிறார்!`,
        "statusPartnerArrived": `பார்ட்னர் வந்துவிட்டார்!`,
        "statusServiceCompleted": `சேவை வெற்றிகரமாக முடிந்தது!`,
        "years": `ஆண்டுகள்`,
        "quickSweep": `விரைவான சுத்தம்`,
        "deepScrub": `ஆழமான சுத்தம்`,
        "ecoWash": `சுற்றுச்சூழல் நட்பு சுத்தம்`,
        "homeAddressSlot": `இல்லம் (12, அசோகா ஹைட்ஸ், புனே)`,
        "officeAddressSlot": `அலுவலகம் (ஃபேஸ் 3, ஹிஞ்சேவாடி, புனே)`,
        "childrenAddressSlot": `பிள்ளைகள் இல்லம் (பிளாக் பி, கோத்ருட், புனே)`,
        "addNewAddressSlot": `புதிய முகவரியைச் சேர்...`,
        "typeAddressPlaceholder": `உங்கள் முழு முகவரியையும் இங்கே தட்டச்சு செய்யவும்...`,
        "Hindi": `ஹிந்தி`,
        "Marathi": `மராத்தி`,
        "English": `ஆங்கிலம்`,
        "Gujarati": `குஜராத்தி`,
        "Bengali": `பெங்காலி`,
        "Telugu": `தெலுங்கு`,
        "Tamil": `தமிழ்`, voice: 'ta-IN', name: 'Tamil', nativeName: 'தமிழ்' },
  te: {
        "gpsActive": `జిపిఎస్ యాక్టివ్`,
        "gpsSearching": `జిపిఎస్ వెతుకుతోంది...`,
        "liveTracking": `లైవ్ ట్రాకింగ్`,
        "simMovement": `నడక సిమ్యులేషన్`,
        "stopSimulation": `సిమ్యులేషన్ ఆపు`,
        "shareWithFamily": `కుటుంబానికి పంపు`,
        "latitude": `అక్షాంశం`,
        "longitude": `రేఖాంశం`,
        "speed": `వేగం`,
        "accuracy": `ఖచ్చితత్వం`,
        "gpsActiveText": `లైవ్ జిపిఎస్ ట్రాకింగ్ ప్రారంభమైంది. సిగ్నల్ కోసం వెతుకుతోంది...`,
        "gpsInactiveText": `లైవ్ ట్రాకింగ్ నిలిపివేయబడింది.`,
        "gpsErrorText": `జిపిఎస్ సిగ్నల్ బలహీనంగా ఉంది. దయచేసి పర్మిషన్స్ చెక్ చేయండి.`,
        "simActiveText": `పుణేలో లైవ్ నడక సిమ్యులేషన్ ప్రారంభమైంది.`,
        "simInactiveText": `సిమ్యులేషన్ ఆపబడింది.`,
        "currentLocSpoken": `మీ ప్రస్తుత చిరునామా`,
        "locationSharedSuccess": `లైవ్ లొకేషన్ విజయవంతంగా కుటుంబ సభ్యులతో పంచుకోబడింది!`,
        "cleaningCat": `శుభ్రపరిచే సేవలు`,
        "applianceCat": `ఉపకరణాల మరమ్మతు`,
        "medicineCat": `వైద్య సేవలు`,
        "convenienceCat": `రోజువారీ సేవలు`,
        "safetyCat": `భద్రత & హెచ్చరికలు`,
        "Room Cleaning": `గది శుభ్రత`,
        "Room Cleaning_sub": `ఇల్లు తుడుచుకోవడం, బూజు దులపడం మరియు గది సర్దడం.`,
        "Bathroom Cleaning": `బాత్‌రూమ్ శుభ్రత`,
        "Bathroom Cleaning_sub": `బాత్‌రూమ్స్ మరియు టాయిలెట్స్ డీప్ క్లీనింగ్ మరియు క్రిమిసంహారకం.`,
        "Kitchen Cleaning": `వంటగది శుభ్రత`,
        "Kitchen Cleaning_sub": `వంట స్టవ్, గట్టు కడగడం మరియు పాత్రలు సర్దడం.`,
        "Deep Home Cleaning": `ఇంటి డీప్ క్లీనింగ్`,
        "Deep Home Cleaning_sub": `ఇంటి ప్రతి మూల, కిటికీలు మరియు అన్ని గదుల సంపూర్ణ శుభ్రత.`,
        "Sofa Cleaning": `సోఫా శుభ్రత`,
        "Sofa Cleaning_sub": `సోఫాలు మరియు కుర్చీల దుమ్ము దులపడం మరియు మరకలు తొలగించడం.`,
        "Balcony Cleaning": `బాల్కనీ శుభ్రత`,
        "Balcony Cleaning_sub": `బాల్కనీ ఫ్లోర్ కడగడం మరియు మొక్కల కుండీల చుట్టూ శుభ్రత.`,
        "Floor Cleaning": `నేల శుభ్రత`,
        "Floor Cleaning_sub": `నేల తుడుచుకోవడం మరియు శుభ్రంగా ఉంచడం.`,
        "Stove Repair": `స్టవ్ మరమ్మతు`,
        "Stove Repair_sub": `గ్యాస్ లీకేజ్, బర్నర్ సమస్యలు మరియు స్టవ్ రిపేర్.`,
        "Fan Repair": `ఫ్యాన్ మరమ్మతు`,
        "Fan Repair_sub": `శబ్దం చేసే ఫ్యాన్ రిపేర్ చేయడం, రెగ్యులేటర్ మార్చడం.`,
        "AC Repair": `ఏసీ మరమ్మతు`,
        "AC Repair_sub": `ఏసీ ఫిల్టర్లు క్లీన్ చేయడం మరియు గ్యాస్ లీక్ రిపేర్ చేయడం.`,
        "Refrigerator Repair": `ఫ్రిజ్ మరమ్మతు`,
        "Refrigerator Repair_sub": `ఫ్రిజ్ కూలింగ్ సమస్యలు, శబ్దాలు మరియు కరెంట్ ఫాల్ట్స్ రిపేర్.`,
        "TV Repair": `టీవీ మరమ్మతు`,
        "TV Repair_sub": `టీవీ స్క్రీన్, సౌండ్ సమస్యలు లేదా సెటప్ బాక్స్ కనెక్షన్ రిపేర్.`,
        "Electrician": `ఎలక్ట్రీషియన్ సేవలు`,
        "Electrician_sub": `షార్ట్ సర్క్యూట్స్ రిపేర్, బల్బులు/స్విచ్‌లు మార్చడం.`,
        "Plumber": `ప్లంబర్ సేవలు`,
        "Plumber_sub": `లీకవుతున్న కుళాయిలు రిపేర్, పైపుల బ్లాక్స్ క్లియర్ చేయడం.`,
        "Water Purifier Service": `వాటర్ ప్యూరిఫైర్ సర్వీస్`,
        "Water Purifier Service_sub": `ఆర్ఓ (RO) ఫిల్టర్లు మార్చడం మరియు వాటర్ ట్యాంక్ క్లీన్ చేయడం.`,
        "Mobile Repair Assistance": `మొబైల్ సహాయం & రిపేర్`,
        "Mobile Repair Assistance_sub": `ఫోన్ సెట్టింగ్స్, యాప్ డౌన్‌లోడ్స్ మరియు చిన్న రిపేర్లలో సహాయం.`,
        "Medicine Delivery": `మందుల పంపిణీ`,
        "Medicine Delivery_sub": `మీరు వాడే మందులను నేరుగా మీ ఇంటికే తెప్పించడం.`,
        "Doctor Appointment": `డాక్టర్ అపాయింట్‌మెంట్`,
        "Doctor Appointment_sub": `దగ్గరలోని నిపుణులైన డాక్టర్ల వద్ద అపాయింట్‌మెంట్ బుకింగ్.`,
        "Video Doctor Consultation": `వీడియో కాల్ డాక్టర్`,
        "Video Doctor Consultation_sub": `ఇంటి నుండే వీడియో కాల్ ద్వారా డాక్టర్‌తో ముఖాముఖి సలహా.`,
        "Nurse Assistance": `ఇంటి వద్ద నర్స్ సహాయం`,
        "Nurse Assistance_sub": `బీపీ, షుగర్ చెక్ చేయడానికి, ఇంజెక్షన్స్ ఇవ్వడానికి నర్స్ హోమ్ విజిట్.`,
        "Blood Test Booking": `రక్త పరీక్షల బుకింగ్`,
        "Blood Test Booking_sub": `ఇంటి వద్దే బ్లడ్ శాంపిల్స్ కలెక్ట్ చేసి రిపోర్ట్స్ పంపే సదుపాయం.`,
        "Health Checkup": `సంపూర్ణ ఆరోగ్య పరీక్ష`,
        "Health Checkup_sub": `ఇంటి నుండే నమూనాల సేకరణతో పూర్తి శరీర ఆరోగ్య పరీక్షల ప్యాకేజీ.`,
        "Physiotherapy": `ఫిజియోథెరపీ సేవలు`,
        "Physiotherapy_sub": `కీళ్ల నొప్పులు, వ్యాయామాల కోసం ఫిజియోథెరపిస్ట్ హోమ్ విజిట్.`,
        "Ambulance Assistance": `అత్యవసర అంబులెన్స్`,
        "Ambulance Assistance_sub": `అత్యవసర సమయాల్లో ఆసుపత్రికి వెళ్ళడానికి అంబులెన్స్ బుకింగ్.`,
        "Grocery Delivery": `కిరాణా సామాను డెలివరీ`,
        "Grocery Delivery_sub": `తాజా కూరగాయలు, పాలు, బ్రెడ్ మరియు కిరాణా వస్తువులు ఇంటికే తెప్పించడం.`,
        "Cab Booking": `క్యాబ్ & ఆటో బుకింగ్`,
        "Cab Booking_sub": `షాపింగ్ లేదా ఆసుపత్రి ప్రయాణాలకు సురక్షితమైన వాహనం బుకింగ్.`,
        "Bill Payment Help": `బిల్లుల చెల్లింపు సహాయం`,
        "Bill Payment Help_sub": `కరెంట్, గ్యాస్, ఫోన్ బిల్లులను ఆన్‌లైన్‌లో సురక్షితంగా చెల్లించడం.`,
        "Document Assistance": `పత్రాల సహాయం`,
        "Document Assistance_sub": `ముఖ్యమైన ప్రభుత్వ పత్రాలను అమర్చడం, ప్రింట్, స్కాన్ చేయడం.`,
        "Bank Visit Assistance": `బ్యాంకుకు వెళ్లే సహాయకుడు`,
        "Bank Visit Assistance_sub": `పాస్ బుక్ ఎంట్రీ, డబ్బు విత్‌డ్రా కోసం బ్యాంకుకు తోడుగా వచ్చే సహాయకుడు.`,
        "Aadhaar/PAN Help": `ఆధార్ & పాన్ కార్డు సహాయం`,
        "Aadhaar/PAN Help_sub": `ఆధార్ వివరాలు సరిచేయడం, పాన్ అప్‌డేట్ లేదా డిజిటల్ కాపీ డౌన్‌లోడ్.`,
        "Companion Visit": `తోడుగా స్నేహితుడు`,
        "Companion Visit_sub": `మాటలు కలపడానికి, పేపర్ చదవడానికి తోడుగా వచ్చే నమ్మకమైన స్నేహితుడు.`,
        "Meal Delivery": `ఇంటి వంటి ఆరోగ్య భోజనం`,
        "Meal Delivery_sub": `వృద్ధుల కోసం తక్కువ నూనె-కారం గల ఆరోగ్యకరమైన ఇంటి భోజనం డెలివరీ.`,
        "Emergency SOS": `అత్యవసర ఎస్ఓఎస్ బటన్`,
        "Emergency SOS_sub": `ఆపదలో ఉన్నప్పుడు పోలీస్, అంబులెన్స్ మరియు పిల్లలకు సమాచారం పంపే బటన్.`,
        "Scam Reporting": `సైబర్ మోసాలపై ఫిర్యాదు`,
        "Scam Reporting_sub": `బ్యాంకు మోసాలు, నకిలీ లాటరీ కాల్స్‌పై సైబర్ క్రైమ్ పోలీస్ ఫిర్యాదు.`,
        "Trusted Contact Alert": `నమ్మకమైన నంబర్ల సెటప్`,
        "Trusted Contact Alert_sub": `అత్యవసర సమయాల కోసం పిల్లల లేదా బంధువుల ఫోన్ నంబర్లు సేవ్ చేయడం.`,
        "Emergency Calling": `అత్యవసర హెల్ప్‌లైన్ కాల్`,
        "Emergency Calling_sub": `ప్రభుత్వ వృద్ధుల హెల్ప్‌లైన్ లేదా అంబులెన్స్‌కు నేరుగా కాల్.`,
        "Nearby Hospital Help": `దగ్గరలోని ఆసుపత్రులు`,
        "Nearby Hospital Help_sub": `అత్యవసర చికిత్స కోసం సమీపంలోని ఆసుపత్రుల వివరాలు కనుగొనడం.`,
        "Live Location Sharing": `కుటుంబంతో లొకేషన్ షేరింగ్`,
        "Live Location Sharing_sub": `మీ భద్రత కొరకు మీ నడక లైవ్ లొకేషన్ పిల్లలతో షేర్ చేయడం.`,
        "Safety Guidance": `మోసాల నివారణ చిట్కాలు`,
        "Safety Guidance_sub": `బ్యాంకు ఖాతా, మొబైల్ ఫోన్స్ సురక్షితంగా ఉంచుకునే చిట్కాలు చదవడం/వినడం.`,
        "Fraud Awareness": `కొత్త మోసాల హెచ్చరికలు`,
        "Fraud Awareness_sub": `మీ ఏరియాలో జరిగే కొత్త కరెంట్ బిల్, కేవైసీ మోసాలపై అలర్ట్స్.`,
        "alertInfoBanner": `ఏం చేయాలో తెలుసుకోవడానికి ఏదైనా అలర్ట్‌పై నొక్కండి. లోపల వినడానికి గైడ్ అందుబాటులో ఉంది.`,
        "staySafe": `ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి`,
        "learnToIdentify": `మోసాలను గుర్తించడం మరియు నివారించడం నేర్చుకోండి`,
        "whatToDo": `చేయవలసినవి:`,
        "highSeverity": `అధిక హెచ్చరిక`,
        "mediumSeverity": `మధ్యస్థ హెచ్చరిక`,
        "selectHelpService": `సహాయక సేవను ఎంచుకోండి`,
        "scheduledFor": `కొరకు షెడ్యూల్ చేయబడింది`,
        "at": `గంటలకు`,
        "today": `ఈరోజు`,
        "tomorrow": `రేపు`,
        "immediate": `వెంటనే`,
        "addressLabel": `చిరునామా`,
        "ratingLabel": `రేటింగ్`,
        "callBtn": `కాల్ చేయండి`,
        "resetBtn": `రీసెట్`,
        "recentlyUsed": `ఇటీవల ఉపయోగించినవి (1-ట్యాప్ బుకింగ్)`,
        "seniorsDeck": `సీనియర్ల డెక్`,
        "oneTapBook": `1-ట్యాప్ బుకింగ్`,
        "noMatchingFound": `సరిపోలే సేవలు ఏవీ కనుగొనబడలేదు.`,
        "trySearchingFor": `"AC", "క్లీనింగ్", "డాక్టర్" లేదా "SOS" కోసం వెతకడానికి ప్రయత్నించండి.`,
        "availableNow": `ప్రస్తుతం అందుబాటులో ఉంది`,
        "pricingPackages": `💰 ప్యాకేజీ ధరలు`,
        "bookSlotOption": `⏱ స్లాట్ బుకింగ్ ఆప్షన్`,
        "selectDateDay": `తేదీ & రోజును ఎంచుకోండి`,
        "selectTimeSlot": `సమయాన్ని ఎంచుకోండి`,
        "languagesLabel": `భాషలు`,
        "addressSelection": `👤 చిరునామా ఎంపిక`,
        "totalPackagesCost": `మొత్తం ప్యాకేజీల ఖరీదు`,
        "confirmBooking": `బుకింగ్‌ను నిర్ధారించండి`,
        "optionsAvailable": `అందుబాటులో ఉన్న ఆప్షన్లు`,
        "availableServices": `అందుబాటులో ఉన్న సేవలు`,
        "closeBtn": `మూసివేయి`,
        "helpersNearby": `సహాయకులు సమీపంలో ఉన్నారు`,
        "closeFollowStatus": `మూసివేసి స్టేటస్ అనుసరించండి`,
        "matchingPartner": `మేము మిమ్మల్ని వెరిఫైడ్, ఫ్రెండ్లీ డిజిసాథీ పార్ట్నర్‌తో కనెక్ట్ చేస్తున్నాము.`,
        "statusPendingPartner": `పార్ట్నర్ కోసం వెతుకుతోంది...`,
        "statusPartnerAssigned": `పార్ట్నర్ కేటాయించబడ్డారు!`,
        "statusOnTheWay": `పార్ట్నర్ దారిలో ఉన్నారు!`,
        "statusPartnerArrived": `పార్ట్నర్ చేరుకున్నారు!`,
        "statusServiceCompleted": `సేవ విజయవంతంగా పూర్తయింది!`,
        "years": `సంవత్సరాలు`,
        "quickSweep": `త్వరిత క్లీనింగ్`,
        "deepScrub": `డీప్ క్లీనింగ్`,
        "ecoWash": `ఎకో వాష్`,
        "homeAddressSlot": `ఇల్లు (12, అశోకా హైట్స్, పూణే)`,
        "officeAddressSlot": `ఆఫీస్ (ఫేజ్ 3, హింజేవాడి, పూణే)`,
        "childrenAddressSlot": `పిల్లల ఇల్లు (బ్లాక్ బి, కోత్రుడ్, పూణే)`,
        "addNewAddressSlot": `కొత్త చిరునామాను జోడించండి...`,
        "typeAddressPlaceholder": `మీ పూర్తి చిరునామాను ఇక్కడ రాయండి...`,
        "Hindi": `హిందీ`,
        "Marathi": `మరాఠీ`,
        "English": `ఇంగ్లీష్`,
        "Gujarati": `గుజరాతీ`,
        "Bengali": `బెంగాలీ`,
        "Telugu": `తెలుగు`,
        "Tamil": `తమిళ`, voice: 'te-IN', name: 'Telugu', nativeName: 'తెలుగు' }
};

export const translations = {
  en: {
    // Splash
    taglines: ["Learn UPI", "Stay Safe Online", "Connect with Family", "Use DigiLocker"],
    trusted: "Trusted by 10,000+ seniors across India",
    seniorBtn: "I am a Senior Learner",
    volunteerBtn: "I am a Youth Volunteer",
    chooseLang: "Choose language",
    splashSubtitle: "Your trusted digital companion 🙏",
    feat1: "Learn UPI & Payments",
    feat2: "Stay safe from scams",
    feat3: "Get volunteer support",
    
    // Login
    welcomeBack: "Welcome Back! 👋",
    enterOtp: "Enter OTP",
    mobileLabel: "Mobile Number",
    resendOtp: "Didn't receive? Resend OTP",
    enterMobile: "Enter your mobile number to continue",
    sendOtp: "Send OTP",
    verifyContinue: "Verify & Continue",
    newHere: "New here? Register in 2 minutes",
    languageInfo: "Language",
    otpSent: "OTP sent to",
    otpSuccess: "OTP verified successfully ✓",

    // Details
    detailsStep1Title: "Tell us about yourself 😊",
    detailsStep1Sub: "Step 1 of 3: Personal Details",
    placeholderName: "Full Name",
    placeholderAge: "Age",
    nextStep: "Next Step",
    detailsStep2Title: "How would you like to learn?",
    detailsStep2Sub: "Step 2 of 3: Preferences",
    fontSize: "Font Size",
    prefLang: "Preferred Language",
    learnGoals: "Learning Goals",
    detailsStep3Title: "Emergency Contact",
    detailsStep3Sub: "Step 3 of 3: Safety Net",
    safetyTip: "Who should we notify if you need immediate assistance?",
    contactName: "Contact Name",
    relation: "Relation",
    mobileNum: "Mobile Number",
    allowFamily: "Allow family to view my learning progress securely",
    completeSetup: "Complete Setup 🎉",

    // Home
    greeting: "Namaste, {name} ji! 🙏",
    doingGreat: "You're doing great! Let's continue learning today.",
    overallProgress: "Overall Progress",
    completedOf: "{completed} of {total} completed",
    urgentAlert: "⚠️ Urgent Fraud Alert",
    fakeKyc: "Fake KYC scam active. Tap to learn more.",
    startLearning: "Start Learning",
    upcomingSession: "Upcoming Volunteer Session",
    joinCall: "Join Call",
    callVolunteer: "Call Volunteer",

    // Profile
    modulesDone: "Modules Done",
    sessionsDone: "Sessions Done",
    daysActive: "Days Active",
    appSettings: "App Settings",
    emergencyContact: "Emergency Contact",
    myVolunteer: "My Volunteer",
    yourBadges: "Your Badges",
    signOut: "Sign Out Securely",

    // Module & Alerts
    stepOf: "Step {step} of {total}",
    takeQuiz: "Take Quiz",
    back: "Back",
    next: "Next",
    tryAgain: "Try Again",
    backToHome: "Back to Home",
    moduleComplete: "Module Complete! 🎉",
    notQuiteThere: "Not Quite There",
    scoreInfo: "You scored {score} out of {total}",
    questionOf: "Question {current} of {total}",
    submitAnswers: "Submit Answers",
    staySafe: "Stay Safe Online",
    learnToIdentify: "Learn to identify and avoid scams",
    whatToDo: "What to do:",
    tapToExpand: "Tap to expand",
    fraudSimulator: "Fraud Simulator",
    safeOrScam: "Is this transaction safe or a scam?",
    safe: "Safe",
    scam: "Scam",
    correct: "CORRECT! 🎉",
    danger: "DANGER! 🛑",
    tryAnother: "Try Another Example",
    simTitle: "Secure Payment Example",
    reqMoney: "Requesting ₹50,000 for 'Lottery Prize Release'",
    fromKbc: "From: KBC Prize Dept",
    payNow: "PAY NOW",
    enterPinToReceive: "Enter PIN to receive money",

    // Bottom Nav
    navHome: "Home",
    navLearn: "Learn",
    navAlerts: "Alerts",
    navProfile: "Profile",

    badges: {
      firstModule: "First Module",
      fraudFighter: "Fraud Fighter",
      sevenDayStreak: "7-Day Streak"
    },
    askSomething: "Ask something...",
    listeningDotDotDot: "🎙️ Listening...",
    voiceAssistant: "AI Assistant"
  },
  hi: {
    // Splash
    taglines: ["UPI सीखें", "ऑनलाइन सुरक्षित रहें", "परिवार से जुड़ें", "डिजीलॉकर का उपयोग करें"],
    trusted: "भारत भर में 10,000+ वरिष्ठ नागरिकों द्वारा विश्वसनीय",
    seniorBtn: "मैं एक वरिष्ठ शिक्षार्थी हूँ",
    volunteerBtn: "मैं एक युवा स्वयंसेवक हूँ",
    chooseLang: "भाषा चुनें",
    splashSubtitle: "आपका विश्वसनीय डिजिटल साथी 🙏",
    feat1: "UPI और भुगतान सीखें",
    feat2: "घोटालों से सुरक्षित रहें",
    feat3: "स्वयंसेवक सहायता प्राप्त करें",
    
    // Login
    welcomeBack: "वापसी पर स्वागत है! 👋",
    enterOtp: "OTP दर्ज करें",
    mobileLabel: "मोबाइल नंबर",
    resendOtp: "नहीं मिला? OTP पुनः भेजें",
    enterMobile: "जारी रखने के लिए अपना मोबाइल नंबर दर्ज करें",
    sendOtp: "OTP भेजें",
    verifyContinue: "सत्यापित करें और आगे बढ़ें",
    newHere: "नए हैं? 2 मिनट में रजिस्टर करें",
    languageInfo: "भाषा (Language)",
    otpSent: "OTP इस नंबर पर भेजा गया:",
    otpSuccess: "OTP सफलतापूर्वक सत्यापित ✓",

    // Details
    detailsStep1Title: "अपने बारे में बताएं 😊",
    detailsStep1Sub: "चरण 1: व्यक्तिगत जानकारी",
    placeholderName: "पूरा नाम",
    placeholderAge: "उम्र",
    nextStep: "अगला चरण",
    detailsStep2Title: "आप कैसे सीखना चाहेंगे?",
    detailsStep2Sub: "चरण 2: प्राथमिकताएं",
    fontSize: "फ़ॉन्ट का आकार",
    prefLang: "पसंदीदा भाषा",
    learnGoals: "सीखने के लक्ष्य",
    detailsStep3Title: "आपातकालीन संपर्क",
    detailsStep3Sub: "चरण 3: सुरक्षा",
    safetyTip: "तत्काल सहायता की आवश्यकता होने पर हमें किसे सूचित करना चाहिए?",
    contactName: "संपर्क नाम",
    relation: "रिश्ता",
    mobileNum: "मोबाइल नंबर",
    allowFamily: "परिवार को मेरी प्रगति देखने की अनुमति दें",
    completeSetup: "सेटअप पूरा करें 🎉",

    // Home
    greeting: "नमस्ते, {name} जी! 🙏",
    doingGreat: "आप बहुत अच्छा कर रहे हैं! आइए आज सीखना जारी रखें।",
    overallProgress: "कुल प्रगति",
    completedOf: "{total} में से {completed} पूर्ण",
    urgentAlert: "⚠️ तत्काल धोखाधड़ी चेतावनी",
    fakeKyc: "फर्जी KYC घोटाला सक्रिय है। अधिक जानने के लिए टैप करें।",
    startLearning: "सीखना शुरू करें",
    upcomingSession: "आगामी स्वयंसेवक सत्र",
    joinCall: "कॉल में शामिल हों",
    callVolunteer: "स्वयंसेवक को कॉल करें",

    // Profile
    modulesDone: "मॉड्यूल पूर्ण",
    sessionsDone: "सत्र पूर्ण",
    daysActive: "सक्रिय दिन",
    appSettings: "ऐप सेटिंग्स",
    emergencyContact: "आपातकालीन संपर्क",
    myVolunteer: "मेरा स्वयंसेवक",
    yourBadges: "आपके बैज",
    signOut: "सुरक्षित रूप से साइन आउट करें",

    // Module & Alerts
    stepOf: "चरण {step} / {total}",
    takeQuiz: "प्रश्नोत्तरी लें",
    back: "पीछे",
    next: "आगे",
    tryAgain: "फिर से प्रयास करें",
    backToHome: "होम पर वापस जाएं",
    moduleComplete: "मॉड्यूल पूर्ण! 🎉",
    notQuiteThere: "थोड़ी और मेहनत",
    scoreInfo: "आपने {total} में से {score} अंक प्राप्त किए",
    questionOf: "प्रश्न {current} / {total}",
    submitAnswers: "उत्तर सबमिट करें",
    staySafe: "ऑनलाइन सुरक्षित रहें",
    learnToIdentify: "घोटालों को पहचानना और बचना सीखें",
    whatToDo: "क्या करें:",
    tapToExpand: "विस्तार करने के लिए टैप करें",
    fraudSimulator: "धोखाधड़ी सिम्युलेटर",
    safeOrScam: "क्या यह लेन-देन सुरक्षित है या घोटाला?",
    safe: "सुरक्षित",
    scam: "घोटाला",
    correct: "सही! 🎉",
    danger: "खतरा! 🛑",
    tryAnother: "एक और उदाहरण आज़माएं",
    simTitle: "सुरक्षित भुगतान उदाहरण",
    reqMoney: "लॉटरी पुरस्कार जारी करने के लिए ₹50,000 का अनुरोध",
    fromKbc: "द्वारा: KBC पुरस्कार विभाग",
    payNow: "अभी भुगतान करें",
    enterPinToReceive: "पैसे प्राप्त करने के लिए PIN दर्ज करें",

    // Bottom Nav
    navHome: "होम",
    navLearn: "सीखें",
    navAlerts: "अलर्ट",
    navProfile: "प्रोफ़ाइल",

    badges: {
      firstModule: "पहला मॉड्यूल",
      fraudFighter: "धोखाधड़ी सेनानी",
      sevenDayStreak: "7 दिन की स्ट्रीक"
    },
    askSomething: "कुछ पूछें...",
    listeningDotDotDot: "🎙️ सुन रहा हूँ...",
    voiceAssistant: "AI सहायक"
  },
  mr: {
    // Splash
    taglines: ["UPI शिका", "ऑनलाइन सुरक्षित राहा", "कुटुंबाशी कनेक्ट व्हा", "DigiLocker वापरा"],
    trusted: "भारतभरातील १०,०००+ ज्येष्ठ नागरिकांचा विश्वास",
    seniorBtn: "मी ज्येष्ठ नागरिक आहे",
    volunteerBtn: "मी युवा स्वयंसेवक आहे",
    chooseLang: "भाषा निवडा",
    splashSubtitle: "तुमचा विश्वासू डिजिटल सोबती 🙏",
    feat1: "UPI आणि पेमेंट शिका",
    homeCareTitle: "गृह सेवा आणि काळजी",
    homeCareSubtitle: "तुमच्या दाराशी विश्वासू मदत आणि सेवा",
    cleaningCat: "सफाई सेवा",
    applianceCat: "उपकरण दुरुस्ती",
    medicineCat: "वैद्यकीय सेवा",
    convenienceCat: "दैनिक सुविधा",
    safetyCat: "सुरक्षा आणि आणीबाणी",
    feat2: "फसवणुकीपासून सुरक्षित राहा",
    feat3: "स्वयंसेवक मदत मिळवा",
    
    // Login
    welcomeBack: "पुन्हा स्वागत आहे! 👋",
    enterOtp: "OTP प्रविष्ट करा",
    mobileLabel: "मोबाईल नंबर",
    resendOtp: "मिळाला नाही? परत OTP पाठवा",
    enterMobile: "सुरू ठेवण्यासाठी तुमचा मोबाईल नंबर प्रविष्ट करा",
    sendOtp: "OTP पाठवा",
    verifyContinue: "पडताळणी करा आणि पुढे जा",
    newHere: "नवीन आहात? २ मिनिटांत नोंदणी करा",
    languageInfo: "भाषा (Language)",
    otpSent: "OTP या नंबरवर पाठवला:",
    otpSuccess: "OTP पडताळणी यशस्वी ✓",
    greeting: "नमस्कार, {name} जी! 🙏",
    doingGreat: "तुम्ही खूप छान करत आहात! चला आज शिकणे सुरू ठेवूया.",
    overallProgress: "एकूण प्रगती",
    completedOf: "{total} पैकी {completed} पूर्ण झाले",
    startLearning: "शिकणे सुरू करा",
    upcomingSession: "आगामी स्वयंसेवक सत्र",
    navHome: "होम",
    navLearn: "शिका",
    navAlerts: "सूचना",
    navProfile: "प्रोफाइल"
  },
  ta: {
    navHome: "முகப்பு",
    navLearn: "கற்க",
    navAlerts: "விழிப்பூட்டல்கள்",
    navProfile: "சுயவிவரம்",
    greeting: "வணக்கம், {name} ஜி! 🙏",
    chooseLang: "மொழியைத் தேர்ந்தெடுக்கவும்",
    seniorBtn: "நான் மூத்த குடிமகன்",
    volunteerBtn: "நான் இளைஞர் தொண்டர்",
    trusted: "இந்தியா முழுவதும் 10,000+ முதியவர்களின் நம்பிக்கை",
    welcomeBack: "மீண்டும் வருக! 👋",
    verifyContinue: "சரிபார்த்து தொடரவும்",
    splashSubtitle: "உங்கள் நம்பிக்கையான டிஜிட்டல் துணை 🙏",
    feat1: "UPI மற்றும் பணம் செலுத்தலை கற்கவும்",
    feat2: "மோசடிகளில் இருந்து பாதுகாப்பாக இருங்கள்",
    feat3: "தொண்டர்களின் ஆதரவை பெறுங்கள்",
    enterOtp: "OTP ஐ உள்ளிடவும்",
    mobileLabel: "கைபேசி எண்",
    resendOtp: "கிடைக்கவில்லையா? மீண்டும் OTP அனுப்பவும்"
  },
  bn: {
    navHome: "হোম",
    navLearn: "শিখুন",
    navAlerts: "সতর্কতা",
    navProfile: "প্রোফাইল",
    greeting: "নমস্কার, {name} জি! 🙏",
    chooseLang: "ভাষা নির্বাচন করুন",
    seniorBtn: "আমি একজন প্রবীণ শিক্ষাত্রী",
    volunteerBtn: "আমি একজন তরুণ স্বেচ্ছাসেবক",
    trusted: "ভারত জুড়ে ১০,০০০+ প্রবীণের বিশ্বাস",
    welcomeBack: "স্বাগত! 👋",
    verifyContinue: "যাচাই করুন এবং অবিরত করুন",
    splashSubtitle: "আপনার বিশ্বস্ত ডিজিটাল সঙ্গী 🙏",
    feat1: "UPI এবং পেমেন্ট শিখুন",
    feat2: "প্রতারণা থেকে সুরক্ষিত থাকুন",
    feat3: "স্বেচ্ছাসেবক সমর্থন পান",
    enterOtp: "OTP লিখুন",
    mobileLabel: "মোবাইল নম্বর",
    resendOtp: "পাননি? আবার OTP পাঠান"
  },
  gu: {
    taglines: ["UPI શીખો", "ઓનલાઇન સુરક્ષિત રહો", "પરિવાર સાથે જોડાઓ", "DigiLocker વાપરો"],
    trusted: "સમગ્ર ભારતના ૧૦,૦૦૦+ વરિષ્ઠ નાગરિકોનો વિશ્વાસ",
    seniorBtn: "હું એક વરિષ્ઠ શીખનાર છું",
    volunteerBtn: "હું એક યુવા સ્વયંસેવક છું",
    chooseLang: "ભાષા પસંદ કરો",
    splashSubtitle: "તમારો વિશ્વસનીય ડિજિટલ સાથી 🙏",
    feat1: "UPI અને પેમેન્ટ્સ શીખો",
    feat2: "કૌભાંડોથી સુરક્ષિત રહો",
    feat3: "સ્વયંસેવકનો ટેકો મેળવો",
    enterOtp: "OTP નોંધાવો",
    mobileLabel: "મોબાઈલ નંબર",
    resendOtp: "મળ્યો નથી? ફરીથી OTP મોકલો",
    welcomeBack: "પાછા ફરી સ્વાગત છે! 👋",
    enterMobile: "ચાલુ રાખવા માટે તમારો મોબાઈલ નંબર નાખો",
    sendOtp: "OTP મોકલો",
    verifyContinue: "ચકાસો અને આગળ વધો",
    newHere: "નવા છો? ૨ મિનિટમાં નોંધણી કરો",
    languageInfo: "ભાષા (Language)",
    otpSent: "આ નંબર પર OTP મોકલવામાં આવ્યો:",
    otpSuccess: "OTP સફળતાપૂર્વક ચકાસાયો ✓",
    greeting: "નમસ્તે, {name} જી! 🙏",
    doingGreat: "તમે ખૂબ સારું કરી રહ્યા છો! ચાલો આજે શીખવાનું ચાલુ રાખીએ.",
    overallProgress: "કુલ પ્રગતિ",
    completedOf: "{total} માંથી {completed} પૂર્ણ",
    startLearning: "શીખવાનું શરૂ કરો",
    upcomingSession: "આગળનું સ્વયંસેવક સત્ર",
    navHome: "હોમ",
    navLearn: "શીખો",
    navAlerts: "ચેતવણીઓ",
    navProfile: "પ્રોફાઈલ"
  },
  te: {
    taglines: ["UPI నేర్చుకోండి", "ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి", "కుటుంబంతో కనెక్ట్ అవ్వండి", "DigiLocker వాడండి"],
    trusted: "భారతదేశం అంతటా 10,000+ సీనియర్ సిటిజన్ల నమ్మకం",
    seniorBtn: "నేను సీనియర్ అభ్యాసకుడిని",
    volunteerBtn: "నేను యువ వాలంటీర్‌ను",
    chooseLang: "భాషను ఎంచుకోండి",
    splashSubtitle: "మీకు నమ్మకమైన డిజిటల్ సహచరుడు 🙏",
    feat1: "UPI మరియు చెల్లింపులు నేర్చుకోండి",
    feat2: "స్కామ్‌ల నుండి సురక్షితంగా ఉండండి",
    feat3: "వాలంటీర్ మద్దతు పొందండి",
    enterOtp: "OTP ను నమోదు చేయండి",
    mobileLabel: "మొబైల్ నంబర్",
    resendOtp: "రాలేదా? మళ్ళీ OTP పంపండి",
    welcomeBack: "తిరిగి స్వాగతం! 👋",
    enterMobile: "కొనసాగించడానికి మీ మొబైల్ నంబర్ నమోదు చేయండి",
    sendOtp: "OTP పంపండి",
    verifyContinue: "నిర్ధారించి కొనసాగించండి",
    newHere: "కొత్త వారా? 2 నిమిషాల్లో నమోదు చేయండి",
    languageInfo: "భాష (Language)",
    otpSent: "OTP ఈ నంబర్‌కు పంపబడింది:",
    otpSuccess: "OTP విజయవంతంగా ధృవీకరించబడింది ✓",
    greeting: "నమస్తే, {name} జీ! 🙏",
    doingGreat: "మీరు అద్భుతంగా చేస్తున్నారు! నేడు నేర్చుకోవడం కొనసాగిద్దాం.",
    overallProgress: "మొత్తం పురోగతి",
    completedOf: "{total} లో {completed} పూర్తయింది",
    startLearning: "నేర్చుకోవడం ప్రారంభించండి",
    upcomingSession: "రాబోయే స్వచ్ఛంద సమావేశం",
    navHome: "హోమ్",
    navLearn: "నేర్చుకో",
    navAlerts: "హెచ్చరికలు",
    navProfile: "ప్రొఫైల్"
  }
};
